### ISSUE TITLE
Windows GPU accuracy extremely bad

### ISSUE THREAD

**Issue by jonathanponce** [apache/incubator-mxnet#1228]
Hey i'm quite new to mxnet, I followed the installation instructions and succeeded in installing it on windows 8.1 64 bit, I then ran the train_mnist.py --network lenet without a problem, quite slow but the accuracy at the end is good at around 99.2, but when I run it as --network lenet --gpus 0 to use my gpu its definitely a lot faster but the accuracy never gets above 10% which is terrible, there must be something wrong theoretically it should be the same accuracy right? I installed cuda 7.5 and also extracted cuddn v3 just as indicated, everything runs without a problem except the accuracy is terrible, i'm running on a laptop with a nvidia 660m graphics card, it has compute capability 3.0.

After running the file I get Train-accuracy=0.098825

**Comment by piiswrong** [comment]
Here is my output from train_mnist.py:
```
2016-01-09 12:48:47,622 Node[0] start with arguments Namespace(batch_size=128, data_dir='mnist/', gpus=None, kv_store='local', load_epoch=None, lr=0.1, lr_factor=1, lr_factor_epoch=1, model_prefix=None, network='mlp', num_epochs=10, num_examples=60000)
[12:48:51] src/io/iter_mnist.cc:91: MNISTIter: load 60000 images, shuffle=1, shape=(128,784)
[12:48:52] src/io/iter_mnist.cc:91: MNISTIter: load 10000 images, shuffle=1, shape=(128,784)
2016-01-09 12:48:52,053 Node[0] Start training with [cpu(0)]
2016-01-09 12:48:53,105 Node[0] Epoch[0] Batch [50]	Speed: 6447.52 samples/sec	Train-accuracy=0.686719
2016-01-09 12:48:53,829 Node[0] Epoch[0] Batch [100]	Speed: 8836.63 samples/sec	Train-accuracy=0.793828
2016-01-09 12:48:54,660 Node[0] Epoch[0] Batch [150]	Speed: 7707.90 samples/sec	Train-accuracy=0.836302
2016-01-09 12:48:55,366 Node[0] Epoch[0] Batch [200]	Speed: 9064.13 samples/sec	Train-accuracy=0.858555
2016-01-09 12:48:56,192 Node[0] Epoch[0] Batch [250]	Speed: 7749.72 samples/sec	Train-accuracy=0.873969
2016-01-09 12:48:57,027 Node[0] Epoch[0] Batch [300]	Speed: 7662.28 samples/sec	Train-accuracy=0.885052
2016-01-09 12:48:57,808 Node[0] Epoch[0] Batch [350]	Speed: 8206.58 samples/sec	Train-accuracy=0.893951
2016-01-09 12:48:58,552 Node[0] Epoch[0] Batch [400]	Speed: 8606.22 samples/sec	Train-accuracy=0.900723
2016-01-09 12:48:59,377 Node[0] Epoch[0] Batch [450]	Speed: 7758.36 samples/sec	Train-accuracy=0.906563
```
It looks fine. Did you try pulling the newest change and make clean && make?

**Comment by jonathanponce** [comment]
here is mine:

```

C:\mxnet\nocudnn\python\image-classification>D:\Python27\python.exe train_mnist.
py --network lenet --gpus 0
2016-01-09 20:52:15,706 Node[0] start with arguments Namespace(batch_size=128, d
ata_dir='mnist/', gpus='0', kv_store='local', load_epoch=None, lr=0.1, lr_factor
=1, lr_factor_epoch=1, model_prefix=None, network='lenet', num_epochs=10, num_ex
amples=60000)
[20:52:17] D:\chhong\mxnet\src\io\iter_mnist.cc:94: MNISTIter: load 60000 images
, shuffle=1, shape=(128, 1, 28, 28)
[20:52:18] D:\chhong\mxnet\src\io\iter_mnist.cc:94: MNISTIter: load 10000 images
, shuffle=1, shape=(128, 1, 28, 28)
2016-01-09 20:52:18,315 Node[0] Start training with [gpu(0)]
2016-01-09 20:52:20,598 Node[0] Epoch[0] Batch [50]     Speed: 4719.76 samples/s
ec      Train-accuracy=0.096719
2016-01-09 20:52:21,969 Node[0] Epoch[0] Batch [100]    Speed: 4668.13 samples/s
ec      Train-accuracy=0.098203
2016-01-09 20:52:23,334 Node[0] Epoch[0] Batch [150]    Speed: 4688.64 samples/s
ec      Train-accuracy=0.100625
2016-01-09 20:52:24,688 Node[0] Epoch[0] Batch [200]    Speed: 4723.25 samples/s
ec      Train-accuracy=0.100039
2016-01-09 20:52:26,042 Node[0] Epoch[0] Batch [250]    Speed: 4726.74 samples/s
ec      Train-accuracy=0.098344
2016-01-09 20:52:27,424 Node[0] Epoch[0] Batch [300]    Speed: 4634.32 samples/s
ec      Train-accuracy=0.099635
2016-01-09 20:52:28,793 Node[0] Epoch[0] Batch [350]    Speed: 4671.53 samples/s
ec      Train-accuracy=0.099955
```

As you can see the accuracy remains at the 9% range, and even after the 10 epochs it remains the same, as far as the make part, I downloaded and installed pre-built package for gpu from here
https://github.com/dmlc/mxnet/releases

**Comment by piiswrong** [comment]
My output with exactly the same command on linux:
```
python train_mnist.py --network lenet --gpus 0
2016-01-09 14:18:41,245 Node[0] start with arguments Namespace(batch_size=128, data_dir='mnist/', gpus='0', kv_store='local', load_epoch=None, lr=0.1, lr_factor=1, lr_factor_epoch=1, model_prefix=None, network='lenet', num_epochs=10, num_examples=60000)
[14:18:43] src/io/iter_mnist.cc:94: MNISTIter: load 60000 images, shuffle=1, shape=(128, 1, 28, 28)
[14:18:43] src/io/iter_mnist.cc:94: MNISTIter: load 10000 images, shuffle=1, shape=(128, 1, 28, 28)
2016-01-09 14:18:43,402 Node[0] Start training with [gpu(0)]
2016-01-09 14:18:46,866 Node[0] Epoch[0] Batch [50]	Speed: 2515.84 samples/sec	Train-accuracy=0.810000
2016-01-09 14:18:49,499 Node[0] Epoch[0] Batch [100]	Speed: 2431.10 samples/sec	Train-accuracy=0.876484
2016-01-09 14:18:52,040 Node[0] Epoch[0] Batch [150]	Speed: 2518.40 samples/sec	Train-accuracy=0.903073
2016-01-09 14:18:54,563 Node[0] Epoch[0] Batch [200]	Speed: 2537.25 samples/sec	Train-accuracy=0.918750
2016-01-09 14:18:57,251 Node[0] Epoch[0] Batch [250]	Speed: 2380.75 samples/sec	Train-accuracy=0.928750
2016-01-09 14:18:59,741 Node[0] Epoch[0] Batch [300]	Speed: 2570.31 samples/sec	Train-accuracy=0.936120
2016-01-09 14:19:02,343 Node[0] Epoch[0] Batch [350]	Speed: 2459.97 samples/sec	Train-accuracy=0.941897
2016-01-09 14:19:04,880 Node[0] Epoch[0] Batch [400]	Speed: 2523.58 samples/sec	Train-accuracy=0.946660
2016-01-09 14:19:07,560 Node[0] Epoch[0] Batch [450]	Speed: 2387.78 samples/sec	Train-accuracy=0.950122
```
This seems to be a windows specific issue. @hjk41 Could you look into it?

**Comment by jonathanponce** [comment]
Hey I used the monitor to check up on things and something is definitely happening, when I run the program using my cpu, things look quite normal

```

C:\mxnet\nocudnn\python\image-classification>D:\Python27\python.exe train_mnist.py --network lenet
2016-01-09 22:31:09,315 Node[0] start with arguments Namespace(batch_size=128, data_dir='mnist/', gpus=None, kv_store='lo
cal', load_epoch=None, lr=0.1, lr_factor=1, lr_factor_epoch=1, model_prefix=None, network='lenet', num_epochs=10, num_exa
mples=60000)
[22:31:11] D:\chhong\mxnet\src\io\iter_mnist.cc:94: MNISTIter: load 60000 images, shuffle=1, shape=(128, 1, 28, 28)
[22:31:11] D:\chhong\mxnet\src\io\iter_mnist.cc:94: MNISTIter: load 10000 images, shuffle=1, shape=(128, 1, 28, 28)
2016-01-09 22:31:11,933 Node[0] Start training with [cpu(0)]
2016-01-09 22:31:13,413 Node[0] Batch:       1 convolution0_output            0.32209
2016-01-09 22:31:13,413 Node[0] Batch:       1 activation0_output             0.263409
2016-01-09 22:31:13,413 Node[0] Batch:       1 pooling0_output                0.264198
2016-01-09 22:31:13,413 Node[0] Batch:       1 convolution1_output            0.280998
2016-01-09 22:31:13,413 Node[0] Batch:       1 activation1_output             0.259359
2016-01-09 22:31:13,413 Node[0] Batch:       1 pooling1_output                0.283388
2016-01-09 22:31:13,413 Node[0] Batch:       1 flatten0_output                0.283388
2016-01-09 22:31:13,413 Node[0] Batch:       1 fullyconnected0_output         0.246848
2016-01-09 22:31:13,413 Node[0] Batch:       1 activation2_output             0.23317
2016-01-09 22:31:13,413 Node[0] Batch:       1 fullyconnected1_output         0.16215
2016-01-09 22:31:13,413 Node[0] Batch:       1 softmax_output                 0.101191
2016-01-09 22:31:13,413 Node[0] Batch:       1 softmax_backward_data          0.301412
2016-01-09 22:31:13,413 Node[0] Batch:       1 softmax_backward_label         0.0
2016-01-09 22:31:13,413 Node[0] Batch:       1 fullyconnected1_backward_data  0.0376285
2016-01-09 22:31:13,413 Node[0] Batch:       1 fullyconnected1_backward_weight 1.13253
2016-01-09 22:31:13,413 Node[0] Batch:       1 fullyconnected1_backward_bias  3.8101
2016-01-09 22:31:13,413 Node[0] Batch:       1 activation2_backward_data      0.0356833
2016-01-09 22:31:13,413 Node[0] Batch:       1 fullyconnected0_backward_data  0.0252012
2016-01-09 22:31:13,413 Node[0] Batch:       1 fullyconnected0_backward_weight 0.163174
2016-01-09 22:31:13,413 Node[0] Batch:       1 fullyconnected0_backward_bias  0.458921
2016-01-09 22:31:13,413 Node[0] Batch:       1 flatten0_backward_data         0.0252012
2016-01-09 22:31:13,413 Node[0] Batch:       1 pooling1_backward_data         0.0126023
2016-01-09 22:31:13,413 Node[0] Batch:       1 activation1_backward_data      0.0116884
2016-01-09 22:31:13,413 Node[0] Batch:       1 convolution1_backward_data     0.010943
2016-01-09 22:31:13,413 Node[0] Batch:       1 convolution1_backward_weight   0.494861
2016-01-09 22:31:13,413 Node[0] Batch:       1 convolution1_backward_bias     1.24864
2016-01-09 22:31:13,413 Node[0] Batch:       1 pooling0_backward_data         0.00705877
2016-01-09 22:31:13,413 Node[0] Batch:       1 activation0_backward_data      0.00671425
2016-01-09 22:31:13,413 Node[0] Batch:       1 convolution0_backward_data     0.0251948
2016-01-09 22:31:13,428 Node[0] Batch:       1 convolution0_backward_weight   0.832047
2016-01-09 22:31:13,428 Node[0] Batch:       1 convolution0_backward_bias     4.85974
2016-01-09 22:31:13,428 Node[0] Batch:       1 data                           0.33463
2016-01-09 22:31:13,428 Node[0] Batch:       1 convolution0_weight            0.175653
2016-01-09 22:31:13,428 Node[0] Batch:       1 convolution0_bias              0.00379667
2016-01-09 22:31:13,428 Node[0] Batch:       1 convolution1_weight            0.0395973
2016-01-09 22:31:13,428 Node[0] Batch:       1 convolution1_bias              0.000975498
2016-01-09 22:31:13,428 Node[0] Batch:       1 fullyconnected0_weight         0.031241
2016-01-09 22:31:13,428 Node[0] Batch:       1 fullyconnected0_bias           0.000358532
2016-01-09 22:31:13,428 Node[0] Batch:       1 fullyconnected1_weight         0.0393582
2016-01-09 22:31:13,428 Node[0] Batch:       1 fullyconnected1_bias           0.00297664
2016-01-09 22:31:13,428 Node[0] Batch:       1 softmax_label                  5.14174
```

but when I use my gpu, most of the weights are zero, maybe they are being rounded off or something is wrong with the precision?

```
C:\mxnet\nocudnn\python\image-classification>D:\Python27\python.exe train_mnist.py --network lenet --gpus 0
2016-01-09 22:31:49,494 Node[0] start with arguments Namespace(batch_size=128, data_dir='mnist/', gpus='0', kv_store='loc
al', load_epoch=None, lr=0.1, lr_factor=1, lr_factor_epoch=1, model_prefix=None, network='lenet', num_epochs=10, num_exam
ples=60000)
[22:31:51] D:\chhong\mxnet\src\io\iter_mnist.cc:94: MNISTIter: load 60000 images, shuffle=1, shape=(128, 1, 28, 28)
[22:31:52] D:\chhong\mxnet\src\io\iter_mnist.cc:94: MNISTIter: load 10000 images, shuffle=1, shape=(128, 1, 28, 28)
2016-01-09 22:31:52,048 Node[0] Start training with [gpu(0)]
2016-01-09 22:31:52,996 Node[0] Batch:       1 convolution0_output            0.0
2016-01-09 22:31:52,996 Node[0] Batch:       1 activation0_output             152988.0
2016-01-09 22:31:52,996 Node[0] Batch:       1 pooling0_output                0.0
2016-01-09 22:31:52,996 Node[0] Batch:       1 convolution1_output            0.0
2016-01-09 22:31:52,996 Node[0] Batch:       1 activation1_output             32342.0
2016-01-09 22:31:52,996 Node[0] Batch:       1 pooling1_output                0.0
2016-01-09 22:31:52,996 Node[0] Batch:       1 flatten0_output                0.0
2016-01-09 22:31:52,996 Node[0] Batch:       1 fullyconnected0_output         0.0
2016-01-09 22:31:52,996 Node[0] Batch:       1 activation2_output             0.0
2016-01-09 22:31:52,996 Node[0] Batch:       1 fullyconnected1_output         0.0
2016-01-09 22:31:52,996 Node[0] Batch:       1 softmax_output                 0.0
2016-01-09 22:31:52,996 Node[0] Batch:       1 softmax_backward_data          0.0
2016-01-09 22:31:52,996 Node[0] Batch:       1 softmax_backward_label         0.0
2016-01-09 22:31:52,996 Node[0] Batch:       1 fullyconnected1_backward_data  0.0
2016-01-09 22:31:52,996 Node[0] Batch:       1 fullyconnected1_backward_weight 0.0
2016-01-09 22:31:52,996 Node[0] Batch:       1 fullyconnected1_backward_bias  0.0
2016-01-09 22:31:52,996 Node[0] Batch:       1 activation2_backward_data      0.0
2016-01-09 22:31:52,996 Node[0] Batch:       1 fullyconnected0_backward_data  0.0
2016-01-09 22:31:53,013 Node[0] Batch:       1 fullyconnected0_backward_weight 0.0
2016-01-09 22:31:53,013 Node[0] Batch:       1 fullyconnected0_backward_bias  0.0
2016-01-09 22:31:53,013 Node[0] Batch:       1 flatten0_backward_data         0.0
2016-01-09 22:31:53,013 Node[0] Batch:       1 pooling1_backward_data         0.0
2016-01-09 22:31:53,013 Node[0] Batch:       1 activation1_backward_data      0.0
2016-01-09 22:31:53,013 Node[0] Batch:       1 convolution1_backward_data     0.0
2016-01-09 22:31:53,013 Node[0] Batch:       1 convolution1_backward_weight   0.0
2016-01-09 22:31:53,013 Node[0] Batch:       1 convolution1_backward_bias     0.0
2016-01-09 22:31:53,013 Node[0] Batch:       1 pooling0_backward_data         0.0
2016-01-09 22:31:53,013 Node[0] Batch:       1 activation0_backward_data      0.0
2016-01-09 22:31:53,013 Node[0] Batch:       1 convolution0_backward_data     0.0
2016-01-09 22:31:53,013 Node[0] Batch:       1 convolution0_backward_weight   0.0
2016-01-09 22:31:53,013 Node[0] Batch:       1 convolution0_backward_bias     0.0
2016-01-09 22:31:53,013 Node[0] Batch:       1 data                           0.0
2016-01-09 22:31:53,013 Node[0] Batch:       1 convolution0_weight            0.0
2016-01-09 22:31:53,013 Node[0] Batch:       1 convolution0_bias              0.0
2016-01-09 22:31:53,013 Node[0] Batch:       1 convolution1_weight            0.0
2016-01-09 22:31:53,013 Node[0] Batch:       1 convolution1_bias              0.0
2016-01-09 22:31:53,013 Node[0] Batch:       1 fullyconnected0_weight         39.2047
2016-01-09 22:31:53,013 Node[0] Batch:       1 fullyconnected0_bias           0.0
2016-01-09 22:31:53,013 Node[0] Batch:       1 fullyconnected1_weight         0.0
2016-01-09 22:31:53,013 Node[0] Batch:       1 fullyconnected1_bias           390.408
2016-01-09 22:31:53,013 Node[0] Batch:       1 softmax_label                  0.0
```

**Comment by piiswrong** [comment]
Could you try to do some simple arithmetic on gpu with 
```Python
x = mx.nd.zeros((10,10), ctx=mx.gpu(0))
x[:] = 1
x = x*2
print x.asnumpy()
```

**Comment by jonathanponce** [comment]
It returns an array of zeros, seems as if the operations are not taking place or are all returning zero

```
>>> print x.asnumpy()
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
```

**Comment by piiswrong** [comment]
Could you try to run cuda's sample code for matrix multiply and see if the
results are normal?

**Comment by jonathanponce** [comment]
I ran the sample code and everything seems to be ok

```
[Matrix Multiply Using CUDA] - Starting...
GPU Device 0: "GeForce GTX 660M" with compute capability 3.0

MatrixA(320,320), MatrixB(640,320)
Computing result using CUDA Kernel...
done
Performance= 4.40 GFlop/s, Time= 29.805 msec, Size= 131072000 Ops, WorkgroupSize
= 1024 threads/block
Checking computed result for correctness: Result = PASS

NOTE: The CUDA Samples are not meant for performance measurements. Results may v
ary when GPU Boost is enabled.
```

The results are as expected

**Comment by piiswrong** [comment]
I can't reproduce the problem locally so I can't think of anything now.
You can try git bisect https://git-scm.com/docs/git-bisect to see if it's a recently introduced bug.

**Comment by jonathanponce** [comment]
I tried out the previous Windows build and it worked without a problem, so that means windows binary build 20160106 has a bug in the gpu computation section, there have been 29 commits since then so its possible that it has been fixed already.

**Comment by JohanManders** [comment]
Even if it is just to back @jonathanponce, I have exactly the same problem. Running train_mnist.py without the --gpus 0 command gives an accuracy of about 0.97, but running with --gpus 0 gives an accuracy of about 0.07

I use Windows 7 64bit with Python 2.7 and have tried windows binary build 20160120 and windows binary build 20160113. Both have the same problem for me.

**Comment by piiswrong** [comment]
@hjk41 Looks like gpu code is not running but not reporting error on windows with their cards. Could you look into it?

**Comment by JohanManders** [comment]
@piiswrong I watched the gpu load with GPU-Z when running the mxnet code and the gpu load is around 25%, so the code is using my gpu.

**Comment by Quares** [comment]
This post reports on the same issue:
https://www.kaggle.com/c/second-annual-data-science-bowl/forums/t/18079/end-to-end-deep-learning-tutorial-0-0392/105458#post105458

I ran into the same situation as well. Not sure yet if the earlier releases solve the problem.

**Comment by gpapadop79** [comment]
Same issue here with mxnet and python. I installed the latest windows build 20160202 and while training a network the accuracy wasn't increasing. The computation was taking placing on the gpu because I checked it with gpu-z.... 
Did the simple arithmetic tests on gpu  mentioned by @piiswrong and it gave me zeroes.

So I switched to the 20151228 build and now it works ok.

So definately the bug from 20160106 still exists in 20160202. Hope it helps.....

**Comment by hjk41** [comment]
@piiswrong @Quares @JohanManders @gpapadop79 
Sorry it take me so long to respond. I was fully occupied with an internal conference last few weeks. I just tried with 20160202 and simple test seems to work alright for me. I guess it must be something in the system configuration side. I am using Windows Server 2012 Datacenter, Python 2.7.10 x64. I will try to switch to some other platform and see if it works there.

Meanwhile, could you help me narrow down the problem a little bit? Here are some speculations:
1. run "where libmxnet.dll" and see if you are using the right version of libmxnet.dll
2. run matrixMulCuBLAS from nvidia CUDA samples and see if it works
3. try building mxnet from source and do the test again

```
Python 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import mxnet as mx
OpenCV is unavailable.
>>> a = mx.nd.ones((2,3), mx.gpu(0))
>>> a.asnumpy()
array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]], dtype=float32)
>>> x = mx.nd.zeros((10,10), ctx=mx.gpu(0))
>>> x[:] = 1
>>> x = x*2
>>> print x.asnumpy()
[[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]]
```

**Comment by hjk41** [comment]
Just tried on another machine with Windows Server 2012R2, Python 2.7.10 x64, it also works fine. :-(
I think I need some help here. It would be great if someone is willing to share a machine that can reproduce the problem.

**Comment by piiswrong** [comment]
Looks like it's caused by low cuda compute capability GPUs.

**Comment by hjk41** [comment]
Could be. I am running Titan. Does this also occur for low compute capability GPUs on Linux?

**Comment by JohanManders** [comment]
I have a GTX 670 and when I boot into Ubuntu, mxnet works fine. In Windows I cannot get it to work.

I ran some tests on my Windows 7 64bit, using windows binary build 20160216. Using a build earlier, does the same for me.

- libmxnet.dll is in the right place

```
C:\Users\XXXXX>where libmxnet.dll
C:\Anaconda\Lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\libmxnet.dll
```

- matrixMulCuBLAS passes

```
C:\ProgramData\NVIDIA Corporation\CUDA Samples\v7.5\bin\win64\Release>matrixMulC
UBLAS.exe
[Matrix Multiply CUBLAS] - Starting...
GPU Device 0: "GeForce GTX 670" with compute capability 3.0`

MatrixA(640,480), MatrixB(480,320), MatrixC(640,320)
Computing result using CUBLAS...done.
Performance= 1059.89 GFlop/s, Time= 0.185 msec, Size= 196608000 Ops
Computing result using host CPU...done.
```
- but mxnet gives me 0. 0. 0.

```
Python 2.7.11 |Anaconda 2.3.0 (64-bit)| (default, Jan 29 2016, 14:26:21) [MSC v.
1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import mxnet as mx
>>> a = mx.nd.ones((2,3), mx.gpu(0))
>>> a.asnumpy()
array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]], dtype=float32)
>>> x = mx.nd.zeros((10,10), ctx=mx.gpu(0))
>>> x[:] = 1
>>> x = x*2
>>> print x.asnumpy()
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
>>>
```

**Comment by hjk41** [comment]
@jonathanponce So it is not related to compute capability, since both GTX670 and Titan have compute capability 3.0.
Could you try to run a C++ program? You can try to this one:
https://github.com/hjk41/MxNet.cpp.git

Checkout the *test* branch and copy libmxnet.lib/libmxnet.dll to lib/windows/, then build the solution in windows/vs/MxNetTestApp/MxNetTestApp.sln with *x64*. The program just creates an NDArray on GPU, populate it with ones and then print it out. This is pretty much what mx.nd.ones((2,3), mx.gpu(0)) does.

**Comment by hjk41** [comment]
@piiswrong @tqchen @antinucleon 
I just find that both Python and R invokes NDArray::SetValueOp() directly in zeros() and ones(). I think calling C++ member functions from dynamic libraries are pretty dangerous. I am not sure whether it is related to the problem we are facing here. But it will bite us someday. Can we add a C api for SetValueOp so we can avoid the problem?

**Comment by JohanManders** [comment]
@hjk41 Did you want me to do the test? If so, I cloned the test branch, copied the dll and lib file (also needed the lib file) and build the solution successfully. I don't know what should happen or how long it should take, but running the program seems to do nothing.

**Comment by hjk41** [comment]
@JohanManders The program should output a series of digits from 0 to 5. If it prints nothing, then there must b something wrong. It means the problem also occurs for c++ programs.

**Comment by JohanManders** [comment]
@hjk41 Mmm... Strange... Building CUDA samples like marchingCubes, matrixMulCUBLAS and particles seem to be no problem and run perfectly.

**Comment by gpapadop79** [comment]
I also ran matrixMulCUBLAS and it passes. 

My environment is Windows 7 x64 python 2.7.11 (Anaconda 2.5.0) and GTX 960 (which has compute capability 5.2)

**Comment by hjk41** [comment]
Thanks guys. I think I will have to reinstall one of my machines to use Windows 7 to reproduce the problem, which will need some time. Meanwhile, if someone can try to debug the problem, it would be great. With the C++ program, it shouldn't be too hard.

**Comment by Quares** [comment]
So I assume the new (7th) release doesn't solve the issue yet? How is it with you @JohanManders? I haven't had time to work on my desktop to test it yet.

**Comment by JohanManders** [comment]
@Quares I have tried the latest build, Windows binary build 20160216, and I still have the problem.

**Comment by thyu** [comment]
I just found that I have the same problem, tried both mnist and cifar10 examples. I am using GTX980 and Windows 10.

I tried different builds and found that all snapshots after build20151228 do not work, also spotted that the file size has been reduced very much since build 20151228 --- are there changes in compilation config?

**Comment by thyu** [comment]
I tried link to the provided CUDA/CuDNN DLL files and also my own DLLs (same version) via different PATH, did not work either. 

Perhaps it maybe a compiler / OS level issue.

**Comment by hjk41** [comment]
@thyu Could you try the C++ program in the test branch of https://github.com/hjk41/MxNet.cpp.git
I have recreated the problem with a Windows 10 machine in Python, but the C++ program runs just fine

**Comment by thyu** [comment]
Seems fine?

```bash
$ ./MxnetTestApp.exe
0 1 2 3 4 5
```

**Comment by hjk41** [comment]
Yes. So it seems to be something in Python/R binding or how they use the
library.

On Fri, Feb 19, 2016 at 3:34 AM, thyu <notifications@github.com> wrote:

> @hjk41 <https://github.com/hjk41>
> Seems fine?
>
> $ ./MxnetTestApp.exe
> 0 1 2 3 4 5
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/1228#issuecomment-185882232>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by hjk41** [comment]
@thyu @jonathanponce @JohanManders @Quares @piiswrong 
Could you help me check with the latest binary build here? [https://github.com/dmlc/mxnet/releases/tag/20160223](https://github.com/dmlc/mxnet/releases/tag/20160223)
I think it is the problem with CUDA library. Windows Server 2012 and Windows 10/8 uses different CUDA binaries so I assume there is some difference between the libraries we link. The libmxnet.dll compiled on Windows 2012 does not work on Windows 10/8, and vice versa. 

The latest binary was compiled on Windows 10 and it works well on my machine. But I don't have another Windows 10/8/7 machine to test on. So could you help me validate this?

**Comment by JohanManders** [comment]
@hjk41 Your latest builds seems to work perfectly! Thanks man, this helps me a lot! The mnist example now outputs a train accuracy of 0.999 and validation accuracy of 0.991.

**Comment by hjk41** [comment]
@JohanManders Great! I will use Windows 10 in the future for building the binary distribution.

**Comment by Quares** [comment]
Great news! I will test it in the evening and will let you know.

**Comment by gpapadop79** [comment]
@hjk41 The latest build works!!! Thanks!    You rock!!!!

**Comment by gpapadop79** [comment]
@JohanManders @Quares @hjk41 
Did anyone else notice a small decrease in performace on the latest release? 

When I trained a model with the 20151228 release, needed about 15.5 sec/epoch. Now with the latest release training the exact same model takes 18.5 sec/epoch.

**Comment by JohanManders** [comment]
I am happy that it works, but I also see a big speed difference between Windows and Ubuntu. For Windows I downloaded the latest pre-built package 20160223. For Ubuntu I just downloaded the latest version and build it.

I did two tests on my dual-boot i7 system with a GTX 670:

train_mnist.py
```
Windows 7 | Build 20160223                        : ~  6750 samples / sec
Ubuntu    | Downloaded en build a few minutes ago : ~ 20000 samples / sec
```

Training on other data
```
Windows 7 | Build 20160223                        : ~ 49 sec / epoch
Ubuntu    | Downloaded en build a few minutes ago : ~ 31 sec / epoch
```

**Comment by gpapadop79** [comment]
Darn! I must switch to linux! :-P

My speed difference is on win7 between pre-built 20151228 and 20160223. I also tried CuDNN 4 but had no difference.

**Comment by Quares** [comment]
The new release (20160223) works on my Windows10 machine. Great work guys!

Side note: I also noticed (in my case substantial) performance decrease in terms of speed, but that's probably related to various other things happening.

**Comment by thyu** [comment]
The new release works on my machine as well, awesome!

I also observe that Linux is faster than Windows for quite a while, I have Linux box with GTX970 which runs around 700 images per sec something over train_cifar10, but in my company's Windows machine it is only slightly higher than 620 img per sec. It might not be just a single-factor issue and perhaps we can improve it afterwards...

**Comment by hjk41** [comment]
Interesting. I will take a look into it. I expect there to be some
performance difference between Windows and Linux, but didn't expect it to
be so huge.

On Wed, Feb 24, 2016 at 7:33 AM, thyu <notifications@github.com> wrote:

> The new release works on my machine as well, awesome!
>
> I also observe that Linux is faster than Windows for quite a while, I have
> Linux box with GTX970 which runs around 700 images per sec something over
> train_cifar10, but in my company's Windows machine it is only slightly
> higher than 620 img per sec. It might not be just a single-factor issue and
> perhaps we can improve it afterwards...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/1228#issuecomment-187965807>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by hjk41** [comment]
Here is my results:
python train_mnist.py:
```
GTX980, Windows 10:               20000 samples/sec
Titan, Ubuntu 14.04:                  40000 samples/sec
```
Also, CPU runs much faster in this case, at around 50000 samples/sec.

python train_cifa10.py:
```
GTX980, Windows 10:               396 samples/sec
Titan, Ubuntu 14.04:                  445 samples/sec
```

So my guess is that Windows has higher overhead with regard to small GPU operations. In MNIST, the computation is so light that this overhead dominates, and thus CPU > GPU-Linux > GPU-Windows. In Cifa10, there are much less operations and hence the difference is much smaller. Has anyone tried running heavier workloads like ImageNet?

**Comment by gpapadop79** [comment]
@Quares 
According to this: https://github.com/dmlc/mxnet/pull/1449
cudnn 4 is supported

**Comment by Quares** [comment]
@gpapadop79 cool! great to know! I was under the impression about cuddn3 because the documentation doesn't reflect on cuddn4 yet. I am interested to see how the performance changes between cudnn3 and cudnn4. I am running both GTX660Ti and GTX980Ti on two seperate machines so have a nice overview of the performance upgrade between the two cards.

**Comment by xenmind** [comment]
Hi,

Installed the GPU enabled R library (R version: 3.2.3) on Windows 7 today. Looks like it's working on the CPU but not on my GPU. The code seems to execute on the GPU (confirmed with GPU-Z), but error improvement stalls on the second round using example code (as above merged issue), and mx.nd.ones(c(2,3), mx.gpu()) generates a table of 0's not 1's.

I'm using the latest files for everything, and the precompiled GPU package for R. I read in this thread: https://github.com/dmlc/mxnet/issues/250, that indicates 'remove USE_CUDNN' to compile for Cuda Compute GPUs 2.1 (and lower). I'm using a 2.1 GPU. Could this be the problem? 

Could using an earlier 2015 release be a solution? Also might I have to compile my own GPU-enabled files without USE_CUDNN to fix this? I'm hoping I don't have to upgrade my computer to get his working as I'm only doing preliminary testing.

Any help would be appreciated.

Thanks, Gavin.

**Comment by hjk41** [comment]
I haven't tested it on GPU with with compute capability 2.1. I guess the
pre-built binary may not work for you, since it is compiled with compute
capability 3.5. Could you try to compile from source and see if it works?

On Sun, Mar 6, 2016 at 11:49 PM, xenmind <notifications@github.com> wrote:

> Hi,
>
> Installed the GPU enabled R library (R version: 3.2.3) on Windows 7 today.
> Looks like it's working on the CPU but not on my GPU. The code seems to
> execute on the GPU (confirmed with GPU-Z), but error improvement stalls on
> the second round using example code (as above merged issue), and
> mx.nd.ones(c(2,3), mx.gpu()) generates a table of 0's not 1's.
>
> I'm using the latest files for everything, and the precompiled GPU package
> for R. I read in this thread: #250
> <https://github.com/dmlc/mxnet/issues/250>, that indicates 'remove
> USE_CUDNN' to compile for Cuda Compute GPUs 2.1 (and lower). I'm using a
> 2.1 GPU. Could this be the problem?
>
> Could using an earlier 2015 release be a solution? Also might I have to
> compile my own GPU-enabled files without USE_CUDNN to fix this? I'm hoping
> I don't have to upgrade my computer to get his working as I'm only doing
> preliminary testing.
>
> Any help would be appreciated.
>
> Thanks, Gavin.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/1228#issuecomment-192919248>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by xenmind** [comment]
Will do, thanks.

**Comment by xenmind** [comment]
Just wanted to report that compiling the shared dll, with USE_CUDNN turned off worked.

**Comment by jonathanponce** [comment]
The error is back in the latest release the accuracy remain terrible, the 20160223 build works fine, but the rest appear to have the error again

**Comment by hjk41** [comment]
Gosh... Which windows version are you using?

On Tue, Mar 22, 2016 at 8:40 PM, jonathanponce <notifications@github.com>
wrote:

> The error is back in the latest release the accuracy remain terrible, the
> 20160223 build works fine, but the rest appear to have the error again
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/1228#issuecomment-199791777>
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia

**Comment by jonathanponce** [comment]
Windows 8.1

**Comment by wdx04** [comment]
I found the 20160419 binary release has the same problem on my computer, then I compiled mxnet from the latest source and it now works fine.
My hardware and software configurations:
GPU: GTX850M
OS: Windows 8.1 x64
Compiler: Visual Studio 2013 Update 5
3rdparty Software: CUDA 7.5, CUDNN V4, OpenCV 3.1, OpenBLAS 0.2.14
With the default options it produces a 63,658KB libmxnet.dll，with Link-Time Code Generation turned on the size is reduced to 19,900KB, both work fine in GPU mode and the speed is about the same.

**Comment by juanlp** [comment]
Hi wdx04,
Would you mind sharing the compiled libmxnet.dll (63,658kb) or update the instruction. I have same setting but can't make it work.
Thank you.

**Comment by pablozhang** [comment]
Hi @piiswrong @hjk41 

I found the GPU-based mxnet didn't work well on my laptop. I have the same problem about mxnet mentioned above. The performance was very good when using CPU-based mxnet, while the GPU-based method had a low accuracy around 10% on mnist dataset.

My OS is win 10 64-bits, and the device graphic is nividia GTX 960M,  CUDA 7.5. I used 20160531-win 10-baniry-release to install the mxnet on my laptop. In addition, I have tested the CUDA with C and pycuda, both of them were Ok. 

So, I would like ask how to deal with it? Any help could be appreciated. Thank you.

**Comment by wdx04** [comment]
Hi @juanlp ,
You may download my version of libmxnet.dll here(built on 5/22):
http://pan.baidu.com/s/1bzxnvK
I'm facing compiling errors with the latest source so I can't provide the latest libmxnet.dll binary.

**Comment by wdx04** [comment]
Compiling errors are fixed, here is the latest binary:
http://pan.baidu.com/s/1dFrzQet

**Comment by cemkeskin** [comment]
I'm having the same issue. Windows 10 64bit, GTX 1080, VS2013 + CUDA 8.0 + CuDNN v5, Python 2.7.11 x64, compiling from the source code. CPU works fine but GPU fails - remains at 10% for MNIST example. CUDA samples work OK, but a = mx.nd.ones((2,3), mx.gpu(0)) returns all zeros instead of ones. I can't find a solution in the thread above.

**Comment by pablozhang** [comment]
Hi @wdx04,

I downloaded your libmxnet-0612.dll and unpacked it, and put it into the original mxnet file instead of the previous libmxnet.dll. But aftering install it using python setup.py install, there are some mistakes when runing import mxnet. What is up ? Thank you

**Comment by wdx04** [comment]
Hi @pablozhang,
Probably you don't have OpenCV 3.1 and/or cuDNN v4 dlls, my libmxnet.dll was dynamically linked to these libraries, as opposed to the official one. You can download them here:
http://pan.baidu.com/s/1bpbURXt

**Comment by pablozhang** [comment]
Hi @wdx04 ,

I have a confuse about it whether or not I unpack the file and put the two .dll into the 3rdparty file of mxnet is Ok?

**Comment by pablozhang** [comment]
Hi @wdx04,

Thank you for your help, my mxnet does work now. The error has been fixed. Thank you.

**Comment by wdx04** [comment]
Hi @pablozhang,
You are welcome. I think placing the two .dll in any directory listed in your PATH environment variable will be OK.

**Comment by sxjscience** [comment]
Really appreciate the job by @wdx04 . This can be a temporary fix for the problem.

**Comment by cemkeskin** [comment]
@piiswrong @hjk41
The problem persists for CUDA 8.0. Is there a known cause for GPU to fail like this? Is there a known solution?

**Comment by yuantangliang** [comment]
I use pre-builded mxnet 20160531_win10_x64_gpu package and I install cuda_8.0.27_win10,but I still have the same problems. DId anyone know the reason ?

**Comment by yuantangliang** [comment]
@cemkeskin  have you solve you problem? I have the same question with you?

**Comment by genesys64738** [comment]
Here is the problem:
GTX 1080 + CUDA 8.0 = mxnet returns zeros for mx.nd.ones()
GTX 1080 + CUDA 7.5 = curand() doesn't work (NVIDIA issue) and mxnet relies on curand for some tasks. But training on CPU works
So you either need to remove all references to curand (e.g. initialize your arrays manually), or switch back to an older card.

**Comment by long-jian** [comment]
Hi, I got the same problem about training accuracy lower than 10%, I got the same issue like @JohanManders.
I use R 3.3.0, Windows10, cudnn v3, CUDA 7.5, GPU card is GTX 1080.
I tried to create the table like what you did on R, and this might be the reason. And switch the gpu version to cpu works fine.

```
> a = mx.nd.ones(c(2,3), mx.gpu(0))
> a
     [,1] [,2] [,3]
[1,]    0    0    0
[2,]    0    0    0
> a+1
     [,1] [,2] [,3]
[1,]    0    0    0
[2,]    0    0    0
```
```
> a = mx.nd.ones(c(2,3), mx.cpu(0))
> a
     [,1] [,2] [,3]
[1,]    1    1    1
[2,]    1    1    1
> a+1
     [,1] [,2] [,3]
[1,]    2    2    2
[2,]    2    2    2
```

**Comment by yuantangliang** [comment]
I switch From W10 to Ubnutu16.04 ,train minist both on cpu and gpu  work  correctly. My Environment is  GTX 080 + CUDA 8.0  + Ubuntu16.04 ,

**Comment by long-jian** [comment]
Hey, @yuantangliang thanks for sharing. I will try it on ubuntu. I have checked the mxnet C++  version on windows with CUDA 7.5, cudnn v3. It seems works fine. So the problem might be how R using the library of CUDA on windows.

**Comment by long-jian** [comment]
@yuantangliang Hi, thanks for your tips, but I am a totally newbie of ubuntu, while I was trying to compile mxnet of ubuntu for R, I got this message:
```
$ make -j$(nproc)
make: Nothing to be done for `all'.
```
I followed this [page](https://read01.com/zeaJ.html) to edit some lines of the **config.mk** .
```
USE_CUDA = 1 
USE_CUDA_PATH = /usr/local/cuda 
USE_BLAS = atlas
```
I don't know what make this problem. May you help me with it?

**Comment by yuantangliang** [comment]
Did you run cmake first ? you should first run cmake to generate MakeFile.

**Comment by long-jian** [comment]
@yuantangliang Hey, Finally I successfully run mxnet package on R with Ubuntu without the low accurate problem and correctly ones matrix of counting on GPU. Thanks for helping. My environment is GTX1080, Ubuntu 14.04, CUDA 8.0, R 3.3.1. This is a really nice experience to try it on Ubuntu. I learned a lot. :D

**Comment by rfcv** [comment]
Has anyone made R to work with GPU on Windows?

**Comment by long-jian** [comment]
@rfcv not yet, but it works pretty well on ubuntu.

**Comment by juanlp** [comment]
I can confirm that it works fine on Windows and R on the latest version
with CUDA 7.5

**Comment by long-jian** [comment]
@juanlp can't make sure what make my problem, what is your GPU environment?

**Comment by yunzhou** [comment]
I think it is related to cudnn version.
I tested cudnn4+cuda8 in ubuntu 16.04 with gtx1080. I got very bad accuracy.
But I get very good accuracy when change to cudnn5

**Comment by guileryu01** [comment]
I'm having exactly same problem with windows 10 64bit, Visual Studio 2013, CUDA 8.0 RC, CUDNN5, built from source as of 8/10. Has anyone figured out what is the root cause of this issue?

It appears NDArray assignment by numerical value doesn't work, but setting by numpy array is fine, as in this short example.

```
import mxnet
arr = mxnet.ndarray.empty( (2,2), mxnet.gpu(0) )
arr[:] = 1.
arr.asnumpy()
array([[ 0.,  0.],
       [ 0.,  0.]], dtype=float32)
import numpy
arr[:] = numpy.ones((2,2))
arr.asnumpy()
array([[ 1.,  1.],
       [ 1.,  1.]], dtype=float32)

```
Also, when I built mxnet debug version the gpu is working fine, e.g. mnist example converges quickly.

**Comment by auroralinan** [comment]
Same Problem with pre-built20160531 on my win7 64bit and CUDA8.0 RC, CUDNN5, VS2013. Also passed cuda samples' matrix multiply.

I'm going to back to 20160223 and see if it works.

**Comment by thdeltei** [comment]
same issue as everyone, CUDA 7.5, CUDNN3, VS2013, with the latest windows build for GPU, the accuracy is very low, and the matrix test only gives 0.
Reverted to the 20160223 build and it works, 0.9911 on MNIST.

**Comment by cemkeskin** [comment]
Using GTX 1080, CUDA 8.0, CuDNN v5.1, VS2015, Win10, libmxnet.dll built from the source code. Release version still fails with mx.nd.ones, but the debug version works. So the problem is only with the release version.

**Comment by maxint** [comment]
The problem still exists in release `20160531_win10_x64_gpu.7z` and `v0.7.0`. Using GT 740, CUDA 7.5, cuDNN v3, in Win7.

**Comment by qggjonny** [comment]
I have the same problem on release 20160531_win10_x64_gpu.7z:

>>> a=mx.nd.ones((2, 3), mx.gpu())
>>> a.asnumpy()
array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]], dtype=float32)
>>>
>>> b=mx.nd.ones((2, 3), mx.cpu())
>>> b.asnumpy()
array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]], dtype=float32)

**Comment by qggjonny** [comment]
I tested the windows binary build 20160223,it hasn't this problem.

**Comment by qggjonny** [comment]
I tested 20160531_win2012_x64_gpu.7z,it hasn't this bug too

**Comment by yunzhou** [comment]
@qggjonny  Can you share your cudnn version, cuda version and GPU hardware?

I tested 20160223_win10_x64_gpu.7z on cudnn-7.0-win-x64-v3.0-prod.zip, cuda 8.0 and GTX1080.
Still not working.

In [1]: import mxnet as mx
   ...: a=mx.nd.ones((2, 3), mx.gpu())
   ...: print(a.asnumpy())
   ...:
   ...: b=mx.nd.ones((2, 3), mx.cpu())
   ...: print(b.asnumpy())
   ...:
[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]]
Still did not work.

**Comment by qggjonny** [comment]
My cuda version is 7.5,GPU is GT730。
Perhaps you can try 20160531_win2012_x64_gpu.7z

**Comment by auroralinan** [comment]
@qggjonny  When I installed win2012 version and call `import mxnet` in python console, it tells me that `missing cudnn64_70.dll`, but I have put my cudnn in the correct folder and cudnn v5 & v5.1 are both named `cudnn64_5.dll`, can you look at the `3rdparty` folder and see what is your cudnn version?

**Comment by qggjonny** [comment]
I put cudnn64_70.dll in mxnet\3rdparty\cudnn and mxnet\3rdparty\cudnn\bin.

**Comment by MaticsL** [comment]
I have the same problem with `20160531_win10_x64_gpu` and also with `20160531_win2012_x64_gpu`:

```
In [3]: (mxnet.nd.ones((2,2), mxnet.cpu())*100).asnumpy()
Out[3]:
array([[ 100.,  100.],
       [ 100.,  100.]], dtype=float32)

In [4]: (mxnet.nd.ones((2,2), mxnet.gpu())*100).asnumpy()
Out[4]:
array([[ 0.,  0.],
       [ 0.,  0.]], dtype=float32)
```

**Comment by jf003320018** [comment]
I return the 20160223_win10_x64_gpu.7z, the GPU works also.  But in the newest verision, it does not work...

**Comment by yunzhou** [comment]
@jf003320018 I also tried 20160223_win10_x64_gpu.7z, but not work. I use cuda8.0 with cudnn3.
What is your cuda and cudnn?

**Comment by yunzhou** [comment]
@auroralinan Maybe you can try cudnn v3, it has cudnn64_70.dll

**Comment by MaticsL** [comment]
@yunzhou I have the same environment with you and mxnet does not work either.

**Comment by yunzhou** [comment]
@MaticsL  I tried 20160223_win10_x64_gpu.7z + cuda7.5 + cudnn3. The gpu ones functions returns 0
 Also my hardware is gtx1080.
I also notice that even if I put nothing under 3rdparty\cudnn 20160223_win10_x64_gpu, it still runs, but the gpu ones function returns 0.
I will try cuda 7.0 later

**Comment by jf003320018** [comment]
@yunzhou my CUDA is 8.0 and cudnn is V3.  Just following the readme 20160223_win10_x64_gpu.7z, it will work.

**Comment by yunzhou** [comment]
@jf003320018 thanks. Since CUDA 7.0 can not recognize gtx 1080. I will return to CUDA8.0 and try 20160223_win10_x64_gpu.7z.

**Comment by nsndimt** [comment]
i used to compile mxnet with CUDA 8.0 RC  cudnn 5.1 opencv 3.0  mkl in windows 10 and had the this problem too
now, i change  CUDA 8.0 RC to CUDA 8.0 and find no problem
P.S i use gtx 1060

**Comment by sanson87** [comment]
Using R-package, I have this exact problem with:
Windows 10
CUDA 8.0
cudnn V3
GTX 1060
20160531_win10_x64_gpu as well as 20160223_win10_x64_gpu
Does anyone have a reliable solution ?

**Comment by MaticsL** [comment]
@sanson87 You can use prebuild version at [https://github.com/dmlc/mxnet/issues/2813](https://github.com/dmlc/mxnet/issues/2813)

**Comment by sanson87** [comment]
@MaticsL Thanks, do you know how I can build my GPU R-package from those? The folder 3rdparty seems to be missing from the 20161101_mxnet_x64_gpu for instance. Sorry if it's a dumb question.

**Comment by No41Name** [comment]
I have the same problem on windows 10 using
CUDA 8.0
cudnn V3
GeForce 840M
I have tried both 20160531_win10_x64_gpu and 20161104_win10_x64_gpu
but running on GPU the train accuracy remaine always fixed.
Which version can I try to solve this problem?
Thanks.

**Comment by No41Name** [comment]
It seems like this problem can't be solved...

**Comment by cemkeskin** [comment]
Actually compiling from the latest source code with the new CUDA 8.0.44, cuDNN 5.1 and VS2015 worked for me finally. The issue seems to be solved, most likely due to the new CUDA release. With CUDA 8.0.27 only the Debug version was working correctly.

**Comment by No41Name** [comment]
Thanks cemkeskin, but the problem still persists..
I'm using the same versions you mentioned (CUDA 8.0.44, cuDNN 5.1, VS2015), but using the R-Package folder from the GitHub repository (precisely, this: https://github.com/dmlc/mxnet/) and editing with the windows binary build 20160531 (see the first attachment) i get this error when try to installing (see the second attachment). I tried to editing the "NAMESPACE" file removing those names that can't be found, and the installation seems to work, but when i run the models in R under the GPU the train accuracy remains fixed after the second epoch. 
Any suggestion? What do you mean with "compiling from the source code"?

![immagine](https://cloud.githubusercontent.com/assets/23234023/20039784/62221698-a44a-11e6-89ee-58006bff713c.png)
![error-binary-build-may-nosourcecode](https://cloud.githubusercontent.com/assets/23234023/20039787/6d8f2b4c-a44a-11e6-93a0-1a4db8eb30d3.png)

**Comment by No41Name** [comment]
I don't want to be annoying, but can someone help me? I really need a solution

**Comment by hjk41** [comment]
To build MxNet from source, please follow the instructions here:
http://mxnet.io/get_started/setup.html#build-mxnet-on-windows

The prebuilt binary sometimes have strange problems with different OS/CUDA
configurations. Building from source usually solves the problem

**Comment by LinGuanfu** [comment]
When I use the `20160531_win10_x64_gpu.7z`, I have same problem on :
Windows8.1, CUDA 8.0, cuDNN v3 or v5, VS 2015, GTX 860m.
But I do solve this problem by using this [https://github.com/yajiedesign/mxnet/releases ](https://github.com/yajiedesign/mxnet/releases) version, I follow actions:

1. Uninstall mxnet from python. (if you already install it.)
2. Download the `20161125_mxnet_x64_gpu.7z` , unpack it, copy all files into path you previous unpack `20160531_win10_x64_gpu.7z` and replace those there.
3. Do download the cuDNNv4 and unpack it into .../3rdparty/cudnn/
4. Run the `setupenv,cmd` or  set the enviornment path.
5. cd to .../python and type python setup.py install.

There is one thing to note that it requires `cudnn64_4.dll` which belongs to cuDNNv4.

**Comment by noahzn** [comment]
I met the same problem in Ubuntu16.0.4 LTS , CUDA 8.0.44, CuDNN 5.1. And my GPU is Tesla K40c
But this doesn't happen all the time. 
I want to know how to solve this problem, thanks.

**Comment by howard0su** [comment]
I am facing the simliar issue which is even more interesting. I have single binary runs twice and get totally different result.

D:\mxnet\example\image-classification>python train_mnist.py --gpus 0 --network lenet
INFO:root:start with arguments Namespace(batch_size=64, disp_batches=100, gpus='0', kv_store='device', load_epoch=None, lr=0.1, lr_factor=0.1, lr_step_epochs='10', model_prefix=None, mom=0.9, network='lenet', num_classes=10, num_epochs=20, num_examples=60000, num_layers=None, optimizer='sgd', test_io=0, top_k=0, wd=0.0001)
WARNING:root:[91m[Deprecation Warning] mxnet.model.FeedForward has been deprecated. Please use mxnet.mod.Module instead.[0m
INFO:root:Start training with [gpu(0)]
INFO:root:Epoch[0] Batch [100]  Speed: 1418.34 samples/sec      Train-accuracy=0.116719
INFO:root:Epoch[0] Batch [200]  Speed: 1402.49 samples/sec      Train-accuracy=0.101875
INFO:root:Epoch[0] Batch [300]  Speed: 1404.02 samples/sec      Train-accuracy=0.092188
INFO:root:Epoch[0] Batch [400]  Speed: 1404.78 samples/sec      Train-accuracy=0.097656
INFO:root:Epoch[0] Batch [500]  Speed: 1400.95 samples/sec      Train-accuracy=0.107188

I run again, without touch any file or reboot. even in same cmd promot:
D:\mxnet\example\image-classification>python train_mnist.py --gpus 0 --network lenet
INFO:root:start with arguments Namespace(batch_size=64, disp_batches=100, gpus='0', kv_store='device', load_epoch=None, lr=0.1, lr_factor=0.1, lr_step_epochs='10', model_prefix=None, mom=0.9, network='lenet', num_classes=10, num_epochs=20, num_examples=60000, num_layers=None, optimizer='sgd', test_io=0, top_k=0, wd=0.0001)
WARNING:root:[91m[Deprecation Warning] mxnet.model.FeedForward has been deprecated. Please use mxnet.mod.Module instead.[0m
INFO:root:Start training with [gpu(0)]
INFO:root:Epoch[0] Batch [100]  Speed: 1418.85 samples/sec      Train-accuracy=0.823750
INFO:root:Epoch[0] Batch [200]  Speed: 1407.11 samples/sec      Train-accuracy=0.915937
INFO:root:Epoch[0] Batch [300]  Speed: 1405.28 samples/sec      Train-accuracy=0.939063
INFO:root:Epoch[0] Batch [400]  Speed: 1405.67 samples/sec      Train-accuracy=0.948281
INFO:root:Epoch[0] Batch [500]  Speed: 1390.74 samples/sec      Train-accuracy=0.953594
INFO:root:Epoch[0] Batch [600]  Speed: 1344.73 samples/sec      Train-accuracy=0.957031
INFO:root:Epoch[0] Batch [700]  Speed: 1345.86 samples/sec      Train-accuracy=0.955781
INFO:root:Epoch[0] Batch [800]  Speed: 1380.60 samples/sec      Train-accuracy=0.960781
INFO:root:Epoch[0] Batch [900]  Speed: 1350.45 samples/sec      Train-accuracy=0.962344

I bet this is due to some error related to initialization of weights. if i got another repro, i will try to debug.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
