### ISSUE TITLE
/usr/bin/ld: cannot find -lsatlas

### ISSUE THREAD

**Issue by HaichaoZhu** [apache/incubator-mxnet#14235]
## Description
I got an error in when compile mxnet with "make -j4". At last stage, "/usr/bin/ld: cannot find -lsatlas" happened. It looks like:
`a - build/src/kvstore/kvstore_utils.o`
`a - build/src/kvstore/kvstore.o`
`a - build/src/resource.o`
`a - build/src/libinfo.o`
`a - build/src/initialize.o`
`/usr/bin/ld: cannot find -lsatlas`
`collect2: error: ld returned 1 exit status`
`make: *** [lib/libmxnet.so] Error 1`
`make: *** Waiting for unfinished jobs....`
`/usr/bin/ld: cannot find -lsatlas`
`collect2: error: ld returned 1 exit status`
`make: *** [bin/im2rec] Error 1`

## Environment info 

```
----------Python Info----------
('Version      :', '2.7.5')
('Compiler     :', 'GCC 4.8.5 20150623 (Red Hat 4.8.5-28)')
('Build        :', ('default', 'Jul 13 2018 13:06:57'))
('Arch         :', ('64bit', 'ELF'))
------------Pip Info-----------
('Version      :', '8.1.2')
('Directory    :', '/usr/lib/python2.7/site-packages/pip')
----------MXNet Info-----------
No MXNet installed.
----------System Info----------
('Platform     :', 'Linux-3.10.0-862.14.4.el7.x86_64-x86_64-with-centos-7.5.1804-Core')
('system       :', 'Linux')
('node         :', 'spectre11')
('release      :', '3.10.0-862.14.4.el7.x86_64')
('version      :', '#1 SMP Wed Sep 26 15:12:11 UTC 2018')

```

Package used :
Currently Loaded Modulefiles:
   (1) shared                    (3) moab/9.0.2(default)       (5) gcc/6.3.0                 (7) lapack/gcc/3.6.1
   (2) torque/6.0.3(default)     (4) intel/license             (6) openblas/dynamic/0.2.18

**Comment by frankfliu** [comment]
@mxnet-label-bot add [Question, build]

**Comment by lanking520** [comment]
Looks like atlas is missing, please try to install this and try again.
```
yum install atlas-devel
```

**Comment by HaichaoZhu** [comment]
@lanking520 Since I have no rights of administrator, I can not use `yum`. I tried with other methods like `conda install -c anaconda atlas ` and system gives me `# All requested packages already installed`. I can not install `atlas-devel` with `conda`. Should I ask administrator for help? Or installed atlas already has the package, I need to set the path in `bashrc` file?

**Comment by junrushao1994** [comment]
can you try openblas?

**Comment by HaichaoZhu** [comment]
@junrushao1994 I loaded the module `openblas/dynamic/0.2.18 `. But the error `/usr/bin/ld: cannot find -lsatlas` still exits. I think I used openblas already. Since without loading `openblas` module, I would meet another problem "missing file `cblas.h`".

**Comment by lanking520** [comment]
@HaichaoZhu My recommendation. Since you do not have admin access, please try to use the existing pip package directly to use MXNet. If you need to change the code base to build from source, I would recommend to use a VM has cent OS 7 or docker to build as many of the dependencies required admin to install

**Comment by HaichaoZhu** [comment]
@lanking520 Thank you for the suggestions. Unfortunately, I need to change the codes from source. I can not use a VM or docker because the GPU resource will be unavailable with this solution. I think I need to contact administrator to install the package.

**Comment by junrushao1994** [comment]
Did you use Makefile or CMake? If you are using Makefile, please also change [this line](https://github.com/apache/incubator-mxnet/blob/master/make/config.mk#L116) to OpenBlas.

ATLAS and OpenBLAS are different packages, if "cannot find -lsatlas" still exists, there must be somewhere still using ATLAS rather than OpenBLAS.

> @junrushao1994 I loaded the module `openblas/dynamic/0.2.18 `. But the error `/usr/bin/ld: cannot find -lsatlas` still exits. I think I used openblas already. Since without loading `openblas` module, I would meet another problem "missing file `cblas.h`".

**Comment by lanking520** [comment]
> @lanking520 Thank you for the suggestions. Unfortunately, I need to change the codes from source. I can not use a VM or docker because the GPU resource will be unavailable with this solution. I think I need to contact administrator to install the package.

Well, build the GPU package does not mean you have to have a GPU on it. You can follow this instruction to build the package easily with any CUDA version. https://github.com/apache/incubator-mxnet/tree/master/tools/staticbuild. To simplify that, open a 14.04 VM and do the following:
```
sudo ./ci/docker/install/ubuntu_publish.sh
export mxnet_variant=cu92
source tools/staticbuild/build.sh $mxnet_variant pip
```
The `mxnet_variant` is the version you would like to build with (cu80, cu90, cu92) are all valid options

Once you can build a pip package from it, it should be closed to the one we published and allows you directly import to your Cent OS VM to test.

**Comment by HaichaoZhu** [comment]
> Did you use Makefile or CMake? If you are using Makefile, please also change [this line](https://github.com/apache/incubator-mxnet/blob/master/make/config.mk#L116) to OpenBlas.
ATLAS and OpenBLAS are different packages, if "cannot find -lsatlas" still exists, there must be somewhere still using ATLAS rather than OpenBLAS.

Oh, this is the solution! I did use `makefile`, but I didn't know I need to change `USE_BLAS = atlas` in `config file`. Thank you so much. Although there is still some other errors, I don't have `/usr/bin/ld: cannot find -lsatlas` anymore!

**Comment by HaichaoZhu** [comment]
@lanking520 Thank you for the support. If I can build VM without using GPU, it will be helpful for my next stage research. I will try in my computer.

**Comment by junrushao1994** [comment]
@HaichaoZhu please let me know if you have further building issues. Building stuff is kinda fun for me.

**Comment by lanking520** [comment]
>  Building stuff is kinda fun for me.

@junrushao1994 おもしろい面白い!
Please follow the https://cwiki.apache.org/confluence/display/MXNET/Outstanding+problems+with+publishing to see if you would like to contribute our publish problems.

**Comment by HaichaoZhu** [comment]
@junrushao1994 

> please let me know if you have further building issues. Building stuff is kinda fun for me.

In fact, I have further issues. The LAPACK problem. I installed `lapack` package, but `undefined reference to 'ssyevd_'` and `undefined reference to 'dgesvd_'` occurred. Since University's computer is under maintenance, I can not provide the whole error message.

**Comment by junrushao1994** [comment]
[These lines](https://github.com/apache/incubator-mxnet/blob/master/Makefile#L176-L187) in Makefile checks if LAPACK is properly installed. Could you try again and let me know whether there is a warning?

**Comment by HaichaoZhu** [comment]
@junrushao1994  My bad, I did not add lapack path correctly in `config` file. Now the warning disappear. Thank you so much for your suggestions.

**Comment by HaichaoZhu** [comment]
I think I can close this now. Again, thank you for your support. @lanking520 @junrushao1994

**Comment by sheep94lion** [comment]
> Looks like atlas is missing, please try to install this and try again.
> 
> ```
> yum install atlas-devel
> ```

I met the same problem. I installed atlas-devel but the problem still exists. Do I have to specify the path to atlas library with some make variables?
