### ISSUE TITLE
Mxnet doesn't install for R if OpenCV is build on linux

### ISSUE THREAD

**Issue by shawnbrar** [apache/incubator-mxnet#17359]
I am an avid R user and wanted to build Mxnet for R on Ubuntu 18.04.
I have also built (not installed through apt-get) OpenCV with its contributed modules.
For Mxnet, I had installed Intel's MKL library through their repository and had built Intel MKL-DNN library. 
I wanted to build Mxnet for CPU. Below is the cmake command with it's flags that I use to make the cmake files in the build directory.

`cmake -GNinja -DUSE_CUDA=OFF -DUSE_MKL_IF_AVAILABLE=ON -DCMAKE_CUDA_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_BUILD_TYPE=Release -DUSE_MKLDNN=1 -DUSE_OPENCV=ON ..`

Using this, get the following output:- 
______________________________________________
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_CROSSCOMPILING FALSE
-- CMAKE_HOST_SYSTEM_PROCESSOR x86_64
-- CMAKE_SYSTEM_PROCESSOR x86_64
-- CMAKE_SYSTEM_NAME Linux
-- CMake version '3.16.2' using generator 'Ninja'
-- Performing Test SUPPORT_CXX11
-- Performing Test SUPPORT_CXX11 - Success
-- Performing Test SUPPORT_CXX0X
-- Performing Test SUPPORT_CXX0X - Success
-- Performing Test SUPPORT_MSSE3
-- Performing Test SUPPORT_MSSE3 - Success
-- Performing Test SUPPORT_MSSE2
-- Performing Test SUPPORT_MSSE2 - Success
-- Determining F16C support
-- Performing Test COMPILER_SUPPORT_MF16C
-- Performing Test COMPILER_SUPPORT_MF16C - Success
-- F16C enabled
-- MKL-DNN compat: set DNNL_BUILD_EXAMPLES to MKLDNN_BUILD_EXAMPLES with value `OFF`
-- MKL-DNN compat: set DNNL_BUILD_TESTS to MKLDNN_BUILD_TESTS with value `OFF`
-- MKL-DNN compat: set DNNL_ENABLE_JIT_PROFILING to MKLDNN_ENABLE_JIT_PROFILING with value `OFF`
-- MKL-DNN compat: set DNNL_LIBRARY_TYPE to MKLDNN_LIBRARY_TYPE with value `STATIC``
-- MKL-DNN compat: set DNNL_ARCH_OPT_FLAGS to MKLDNN_ARCH_OPT_FLAGS with value ``
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- GPU support is disabled
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.13") found components: doxygen dot 
-- Found Git: /usr/bin/git (found version "2.17.1") 
-- Intel(R) VTune(TM) Amplifier JIT profiling disabled
-- Found MKL: /opt/intel/mkl/include  
-- Found MKL (include: /opt/intel/mkl/include, lib: /opt/intel/mkl/lib/intel64/libmkl_rt.so
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Found Jemalloc: /usr/lib/x86_64-linux-gnu/libjemalloc.so  
-- Using JEMalloc malloc
-- Found OpenCV: /usr/local (found version "4.2.0") found components: core highgui imgproc imgcodecs 
-- OpenCV 4.2.0 found (/usr/local/lib/cmake/opencv4)
--  OpenCV_LIBS=opencv_core;opencv_highgui;opencv_imgproc;opencv_imgcodecs
-- Found OpenMP_C: -fopenmp  
-- Found OpenMP_CXX: -fopenmp  
-- Found OpenMP: TRUE   
-- Performing Test OPENMP_HAVE_WERROR_FLAG
-- Performing Test OPENMP_HAVE_WERROR_FLAG - Success
-- Performing Test OPENMP_HAVE_STD_GNUPP11_FLAG
-- Performing Test OPENMP_HAVE_STD_GNUPP11_FLAG - Success
-- Performing Test OPENMP_HAVE_STD_CPP11_FLAG
-- Performing Test OPENMP_HAVE_STD_CPP11_FLAG - Success
-- Found PythonInterp: /usr/bin/python (found version "2.7.17") 
-- Cannot find llvm-lit.
-- Please put llvm-lit in your PATH, set OPENMP_LLVM_LIT_EXECUTABLE to its full path, or point OPENMP_LLVM_TOOLS_DIR to its directory.
CMake Warning at 3rdparty/openmp/cmake/OpenMPTesting.cmake:22 (message):
  The check targets will not be available!
Call Stack (most recent call first):
  3rdparty/openmp/cmake/OpenMPTesting.cmake:40 (find_standalone_test_dependencies)
  3rdparty/openmp/CMakeLists.txt:49 (include)

-- Performing Test LIBOMP_HAVE_FNO_EXCEPTIONS_FLAG
-- Performing Test LIBOMP_HAVE_FNO_EXCEPTIONS_FLAG - Success
-- Performing Test LIBOMP_HAVE_FNO_RTTI_FLAG
-- Performing Test LIBOMP_HAVE_FNO_RTTI_FLAG - Success
-- Performing Test LIBOMP_HAVE_X_CPP_FLAG
-- Performing Test LIBOMP_HAVE_X_CPP_FLAG - Success
-- Performing Test LIBOMP_HAVE_WCAST_QUAL_FLAG
-- Performing Test LIBOMP_HAVE_WCAST_QUAL_FLAG - Success
-- Performing Test LIBOMP_HAVE_WNO_UNUSED_FUNCTION_FLAG
-- Performing Test LIBOMP_HAVE_WNO_UNUSED_FUNCTION_FLAG - Success
-- Performing Test LIBOMP_HAVE_WNO_UNUSED_LOCAL_TYPEDEF_FLAG
-- Performing Test LIBOMP_HAVE_WNO_UNUSED_LOCAL_TYPEDEF_FLAG - Failed
-- Performing Test LIBOMP_HAVE_WNO_UNUSED_VALUE_FLAG
-- Performing Test LIBOMP_HAVE_WNO_UNUSED_VALUE_FLAG - Success
-- Performing Test LIBOMP_HAVE_WNO_UNUSED_VARIABLE_FLAG
-- Performing Test LIBOMP_HAVE_WNO_UNUSED_VARIABLE_FLAG - Success
-- Performing Test LIBOMP_HAVE_WNO_SWITCH_FLAG
-- Performing Test LIBOMP_HAVE_WNO_SWITCH_FLAG - Success
-- Performing Test LIBOMP_HAVE_WNO_COVERED_SWITCH_DEFAULT_FLAG
-- Performing Test LIBOMP_HAVE_WNO_COVERED_SWITCH_DEFAULT_FLAG - Failed
-- Performing Test LIBOMP_HAVE_WNO_DEPRECATED_REGISTER_FLAG
-- Performing Test LIBOMP_HAVE_WNO_DEPRECATED_REGISTER_FLAG - Failed
-- Performing Test LIBOMP_HAVE_WNO_SIGN_COMPARE_FLAG
-- Performing Test LIBOMP_HAVE_WNO_SIGN_COMPARE_FLAG - Success
-- Performing Test LIBOMP_HAVE_WNO_GNU_ANONYMOUS_STRUCT_FLAG
-- Performing Test LIBOMP_HAVE_WNO_GNU_ANONYMOUS_STRUCT_FLAG - Failed
-- Performing Test LIBOMP_HAVE_WNO_UNKNOWN_PRAGMAS_FLAG
-- Performing Test LIBOMP_HAVE_WNO_UNKNOWN_PRAGMAS_FLAG - Success
-- Performing Test LIBOMP_HAVE_WNO_MISSING_FIELD_INITIALIZERS_FLAG
-- Performing Test LIBOMP_HAVE_WNO_MISSING_FIELD_INITIALIZERS_FLAG - Success
-- Performing Test LIBOMP_HAVE_WNO_MISSING_BRACES_FLAG
-- Performing Test LIBOMP_HAVE_WNO_MISSING_BRACES_FLAG - Success
-- Performing Test LIBOMP_HAVE_WNO_COMMENT_FLAG
-- Performing Test LIBOMP_HAVE_WNO_COMMENT_FLAG - Success
-- Performing Test LIBOMP_HAVE_WNO_SELF_ASSIGN_FLAG
-- Performing Test LIBOMP_HAVE_WNO_SELF_ASSIGN_FLAG - Failed
-- Performing Test LIBOMP_HAVE_WNO_VLA_EXTENSION_FLAG
-- Performing Test LIBOMP_HAVE_WNO_VLA_EXTENSION_FLAG - Failed
-- Performing Test LIBOMP_HAVE_WNO_FORMAT_PEDANTIC_FLAG
-- Performing Test LIBOMP_HAVE_WNO_FORMAT_PEDANTIC_FLAG - Failed
-- Performing Test LIBOMP_HAVE_WSTRINGOP_OVERFLOW_FLAG
-- Performing Test LIBOMP_HAVE_WSTRINGOP_OVERFLOW_FLAG - Success
-- Performing Test LIBOMP_HAVE_MSSE2_FLAG
-- Performing Test LIBOMP_HAVE_MSSE2_FLAG - Success
-- Performing Test LIBOMP_HAVE_FTLS_MODEL_FLAG
-- Performing Test LIBOMP_HAVE_FTLS_MODEL_FLAG - Success
-- Performing Test LIBOMP_HAVE_MMIC_FLAG
-- Performing Test LIBOMP_HAVE_MMIC_FLAG - Failed
-- Performing Test LIBOMP_HAVE_M32_FLAG
-- Performing Test LIBOMP_HAVE_M32_FLAG - Failed
-- Performing Test LIBOMP_HAVE_X_FLAG
-- Performing Test LIBOMP_HAVE_X_FLAG - Success
-- Performing Test LIBOMP_HAVE_WARN_SHARED_TEXTREL_FLAG
-- Performing Test LIBOMP_HAVE_WARN_SHARED_TEXTREL_FLAG - Success
-- Performing Test LIBOMP_HAVE_AS_NEEDED_FLAG
-- Performing Test LIBOMP_HAVE_AS_NEEDED_FLAG - Success
-- Performing Test LIBOMP_HAVE_VERSION_SCRIPT_FLAG
-- Performing Test LIBOMP_HAVE_VERSION_SCRIPT_FLAG - Success
-- Performing Test LIBOMP_HAVE_STATIC_LIBGCC_FLAG
-- Performing Test LIBOMP_HAVE_STATIC_LIBGCC_FLAG - Success
-- Performing Test LIBOMP_HAVE_Z_NOEXECSTACK_FLAG
-- Performing Test LIBOMP_HAVE_Z_NOEXECSTACK_FLAG - Success
-- Performing Test LIBOMP_HAVE_FINI_FLAG
-- Performing Test LIBOMP_HAVE_FINI_FLAG - Success
-- Found Perl: /usr/bin/perl (found version "5.26.1") 
-- Performing Test LIBOMP_HAVE_VERSION_SYMBOLS
-- Performing Test LIBOMP_HAVE_VERSION_SYMBOLS - Success
-- Performing Test LIBOMP_HAVE___BUILTIN_FRAME_ADDRESS
-- Performing Test LIBOMP_HAVE___BUILTIN_FRAME_ADDRESS - Success
-- Performing Test LIBOMP_HAVE_WEAK_ATTRIBUTE
-- Performing Test LIBOMP_HAVE_WEAK_ATTRIBUTE - Success
-- Looking for include files windows.h, psapi.h
-- Looking for include files windows.h, psapi.h - not found
-- Looking for EnumProcessModules in psapi
-- Looking for EnumProcessModules in psapi - not found
-- LIBOMP: Operating System     -- Linux
-- LIBOMP: Target Architecture  -- x86_64
-- LIBOMP: Build Type           -- Release
-- LIBOMP: Library Kind         -- SHARED
-- LIBOMP: Library Type         -- normal
-- LIBOMP: Fortran Modules      -- FALSE
-- LIBOMP: Build                -- 20140926
-- LIBOMP: Use Stats-gathering  -- FALSE
-- LIBOMP: Use Debugger-support -- FALSE
-- LIBOMP: Use ITT notify       -- TRUE
-- LIBOMP: Use OMPT-support     -- TRUE
-- LIBOMP: Use OMPT-optional  -- TRUE
-- LIBOMP: Use Adaptive locks   -- TRUE
-- LIBOMP: Use quad precision   -- TRUE
-- LIBOMP: Use TSAN-support     -- FALSE
-- LIBOMP: Use Hwloc library    -- FALSE
-- Looking for sqrt in m
-- Looking for sqrt in m - found
-- Looking for __atomic_load_1
-- Looking for __atomic_load_1 - not found
-- Looking for __atomic_load_1 in atomic
-- Looking for __atomic_load_1 in atomic - found
-- check-libomp does nothing.
-- check-ompt does nothing.
-- check-openmp does nothing.
USE_LAPACK is ON
CMake Warning at 3rdparty/googletest/googletest/CMakeLists.txt:47 (project):
  VERSION keyword not followed by a value or was followed by a value that
  expanded to nothing.

-- Found GTest: gtest  
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - found
-- Looking for fopen64
-- Looking for fopen64 - not found
-- Looking for C++ include cxxabi.h
-- Looking for C++ include cxxabi.h - found
-- Looking for nanosleep
-- Looking for nanosleep - found
-- Looking for backtrace
-- Looking for backtrace - found
-- backtrace facility detected in default set of libraries
-- Found Backtrace: /usr/include  
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- /home/shawnbrar/Documents/Books/mxnet/3rdparty/dmlc-core/cmake/build_config.h.in -> include/dmlc/build_config.h
-- Found OpenMP_C: -fopenmp  
-- Found OpenMP_CXX: -fopenmp  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/shawnbrar/Documents/Books/mxnet/build
______________________________________________

So it finds OpenCV and gives the following output:
`-- Found OpenCV: /usr/local (found version "4.2.0") found components: core highgui imgproc imgcodecs 
-- OpenCV 4.2.0 found (/usr/local/lib/cmake/opencv4)
--  OpenCV_LIBS=opencv_core;opencv_highgui;opencv_imgproc;opencv_imgcodecs`

After this I build the Mxnet library using the following command:
`ninja -v`
This properly compiles my Mxnet library and also creates a _libmxnet.so_ in the _build_ directory.

After this I make the R-package with the following command
`make -f R-package/Makefile rpkg`

This gives me the following error :
`im2rec.cc:39:10: fatal error: opencv2/opencv.hpp: No such file or directory #include <opencv2/opencv.hpp>`

However, after reading this, I installed `libopencv-dev` using the following command
`sudo apt-get install libopencv-dev`
This installed some binaries. After this is installed, I again make the R-package with the same command that I used earlier. But this makes the R package properly.

Why does this happen? Why isn't _mxnet_ using the OpenCV which I had earlier built earlier?

Thanks

**Comment by leezu** [comment]
You likely didn't set up your CPATH, LIBRARY_PATH and LD_LIBRARY_PATH correctly. Could you post the value of each?

Ie run `echo CPATH` etc

**Comment by shawnbrar** [comment]
I actually found the problem. When I type in `make -f R-package/Makefile rpkg`, the following output appears : 
`make -f R-package/Makefile rpkg`

--------------------------------------------------------------------------------------------------------------------
mkdir -p R-package/inst/libs
cp src/io/image_recordio.h R-package/src
if [ -d "lib" ]; then \
	cp -rf lib/libmxnet.so R-package/inst/libs; \
	if [ -e "lib/libtvm_runtime.so" ]; then \
		cp -rf lib/libtvm_runtime.so R-package/inst/libs; \
	fi; \
else \
	cp -rf build/libmxnet.so R-package/inst/libs; \
	if [ -e "build/libtvm_runtime.so" ]; then \
		cp -rf build/libtvm_runtime.so R-package/inst/libs; \
	fi; \
fi
mkdir -p R-package/inst/include
cp -rl include/* R-package/inst/include
Rscript -e "if(!require(devtools)){install.packages('devtools', repo = 'https://cloud.r-project.org/')}"
Loading required package: devtools
Loading required package: usethis
Rscript -e "if(!require(roxygen2)||packageVersion('roxygen2') < '6.1.1'){install.packages('roxygen2', repo = 'https://cloud.r-project.org/')}"
Loading required package: roxygen2
Rscript -e "library(devtools); library(methods); options(repos=c(CRAN='https://cloud.r-project.org/')); install_deps(pkg='R-package', dependencies = TRUE)"
Loading required package: usethis

cp R-package/dummy.NAMESPACE R-package/NAMESPACE  # NAMESPACE will be replaced by devtools::document later
echo "import(Rcpp)" >> R-package/NAMESPACE
R CMD INSTALL R-package
* installing to library ‘/home/shawnbrar/R/x86_64-pc-linux-gnu-library/3.6’
* installing *source* package ‘mxnet’ ...
** using staged installation
** libs
make[1]: Entering directory '/home/shawnbrar/Documents/Libs/mxnet/R-package/src'
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -I../inst/include `pkg-config --cflags opencv` `Rscript -e 'Rcpp:::CxxFlags()'` -I"/home/shawnbrar/R/x86_64-pc-linux-gnu-library/3.6/Rcpp/include"   -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-t3diwe/r-base-3.6.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c im2rec.cc -o im2rec.o
Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found
im2rec.cc:39:10: fatal error: opencv2/opencv.hpp: No such file or directory
 #include <opencv2/opencv.hpp>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
/usr/lib/R/etc/Makeconf:175: recipe for target 'im2rec.o' failed
make[1]: *** [im2rec.o] Error 1
make[1]: Leaving directory '/home/shawnbrar/Documents/Libs/mxnet/R-package/src'
ERROR: compilation failed for package ‘mxnet’
* removing ‘/home/shawnbrar/R/x86_64-pc-linux-gnu-library/3.6/mxnet’
* restoring previous ‘/home/shawnbrar/R/x86_64-pc-linux-gnu-library/3.6/mxnet’
R-package/Makefile:5: recipe for target 'rpkg' failed
make: *** [rpkg] Error 1
--------------------------------------------------------------------------------------------------------------------

In this the following is important to see : 
`g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -I../inst/include 'pkg-config --cflags opencv'`

It says `pkg-config --cflags opencv`
Whereas it should be `pkg-config --cflags opencv4`.

What can I do to make this change? Should I rename my _opencv4.pc_ file to _opencv.pc_?

**Comment by shawnbrar** [comment]
I renamed all of my _opencv4.pc_ files to _opencv.pc_. This solution worked for me.
![Screenshot from 2020-01-22 11-11-41](https://user-images.githubusercontent.com/59639827/72868426-fe602280-3d07-11ea-9034-17c56e2705b5.png)
*Providing with a screenshot*

**Comment by leezu** [comment]
> It says `pkg-config --cflags opencv`
> Whereas it should be `pkg-config --cflags opencv4`

@shawnbrar Do you have any reference for this statement? If so, we need to update 

https://github.com/apache/incubator-mxnet/blob/b295d13491895a5ac9bd4ca186e9260da10774ef/R-package/src/Makevars#L2-L4

accordingly. However, I tested the changes with `pkg-config --cflags opencv` and it works fine on my Ubuntu 18.04.. There is likely something wrong in the way you installed OpenCV.

Let's reopen this issue until your reference above is clarified.

**Comment by leezu** [comment]
@shawnbrar how did you generate `opencv4.pc`? I tried compiling OpenCV 4.2 from source but didn't get a `opencv4.pc`.

In any case, this issue can be fixed by the following patch:

``` patch
modified   R-package/src/Makevars
@@ -1,4 +1,4 @@
 CXX_STD = CXX11
-PKG_LIBS = $(LAPACK_LIBS) $(BLAS_LIBS) `pkg-config --libs opencv`
-PKG_CFLAGS = `pkg-config --cflags opencv`
-PKG_CPPFLAGS = -I../inst/include `pkg-config --cflags opencv` `Rscript -e 'Rcpp:::CxxFlags()'`
+PKG_LIBS = $(LAPACK_LIBS) $(BLAS_LIBS) `(pkg-config --cflags opencv || pkg-config --cflags opencv4)`
+PKG_CFLAGS = `(pkg-config --cflags opencv || pkg-config --cflags opencv4)`
+PKG_CPPFLAGS = -I../inst/include `(pkg-config --cflags opencv || pkg-config --cflags opencv4)` `Rscript -e 'Rcpp:::CxxFlags()'`
```

**Comment by shawnbrar** [comment]
> > It says `pkg-config --cflags opencv`
> > Whereas it should be `pkg-config --cflags opencv4`
> 
> @shawnbrar Do you have any reference for this statement? If so, we need to update
> 
> https://github.com/apache/incubator-mxnet/blob/b295d13491895a5ac9bd4ca186e9260da10774ef/R-package/src/Makevars#L2-L4
> 
> accordingly. However, I tested the changes with `pkg-config --cflags opencv` and it works fine on my Ubuntu 18.04.. There is likely something wrong in the way you installed OpenCV.
> 
> Let's reopen this issue until your reference above is clarified.

So earlier when you had pointed out that I should run some `echo` commands in my terminal, I did not get any output in my terminal. So I went ahead and searched for `opencv` in my system. I found out that I had three different versions on `opencv` on my computer. Two of which were `OpenCV 4.2.0-dev` (the one which I had compiled) and `OpenCV 3.2` (which I had installed from `apt-get`). The third version was `OpenCV 4.1.1` which I think I might have compiled earlier. Since I am not so great at properly uninstalling softwares in Ubuntu, I formatted my hard-drive and did a fresh install of Ubuntu. Then, I built `OpenCV 4.2.0-dev` using the following commands : 
________________________________________________________________________________
sudo apt-get update
sudo apt-get dist-upgrade
sudo apt-get install libavcodec-dev libavformat-dev libswscale-dev libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev
sudo apt-get install libgtk-3-dev
sudo apt purge libx264-dev x264
sudo apt-get install build-essential cmake pkg-config libjpeg8-dev libtiff5-dev libpng12-0
sudo apt install v4l-utils libv4l-dev libgphoto2-dev libgstreamer1.0-0 libgstreamer1.0-dev x264
cd /usr/include/linux/
sudo ln -s -f ../libv4l1-videodev.h videodev.h
cd ~/opencv
cd ./opencv && mkdir build && cd build
sudo apt install libavcodec-dev libavformat-dev libswscale-dev libxvidcore-dev
sudo apt install libgtk-3-dev libatlas-base-dev gfortran python3.6-dev python2.7-dev libtiff-dev

cmake -D CMAKE_BUILD_TYPE=RELEASE -D WITH_V4L=ON -D CMAKE_INSTALL_PREFIX=/usr/local -D INSTALL_PYTHON_EXAMPLES=ON  -D INSTALL_C_EXAMPLES=OFF -D PYTHON_EXECUTABLE=/usr/bin/python3.6  -D BUILD_EXAMPLES=ON -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules -D OPENCV_GENERATE_PKGCONFIG=ON ..
make -j4
make
sudo make install
sudo ldconfig
________________________________________________________________________________
This time I had added an extra flag in the cmake command : `-D OPENCV_GENERATE_PKGCONFIG=ON`. The official documentation of OpenCV does say that if one wants to generate pkg-config info, one should add this flag when running CMake. This is quoted from the step number 6 in their official installation instructions at the following link : 
[OpenCV-4.2.0-dev_Linux_Installation](https://docs.opencv.org/trunk/d7/d9f/tutorial_linux_install.html) 

The official documentation also says "Installed as `opencv4`, usage: `pkg-config --cflags --libs opencv4`" 

After compilation I ran the command `pkg-config --cflags --libs opencv4`, the OpenCV 4 flags and libraries were returning their proper output. 

Next I installed R and Rstudio.
Next I installed Intel's MKL and build MKL-DNN.
After that I build MXNet with the following cmake options:
`cmake -GNinja -DUSE_CUDA=OFF -DUSE_MKL_IF_AVAILABLE=ON -DCMAKE_CUDA_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_BUILD_TYPE=Release -DUSE_MKLDNN=1 -DUSE_OPENCV=ON ..`
`ninja -v`

After this just to check if the library was built properly, I installed it for Python-3. In `python3`, I ran `import mxnet`, and it was working. All the modules and functions were appearing. 

So then I ran the following command to make the R-Package : 
`make -f R-package/Makefile rpkg`

It ran and the problem was still there. It still gave the error : 
`Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing 'opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found`

So I ran the following command to see my PKG_CONFIG_PATH:
`pkg-config --variable pc_path pkg-config`
The output was as following:
`/usr/local/lib/x86_64-linux-gnu/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig`

Since there were six paths and I could only find one `opencv4.pc` file, I copied it to all the other paths. Then, I ran the command to make the R-Package, but the error still persisted. But then I also looked at the error this time and saw that while building the R-Package, it said `pkg-config --cflags opencv`. But according to the OpenCV's documentation and my own computer's configuration it should've been `pkg-config --cflags opencv4`. 

This is when, I asked my second question if I should rename my `opencv4.pc` file to `opencv.pc`
https://github.com/apache/incubator-mxnet/issues/17359#issuecomment-577014464

After a few minutes, I decided to renamed all the `opencv4.pc` files to `opencv.pc` but I did not change any of the file's contents. And I was able to build my R-Package successfully. 
Then I posted that screenshot showing the functions in the mxnet library.(https://github.com/apache/incubator-mxnet/issues/17359#issuecomment-577017711)

I don't know why your opencv's build makes the file opencv.pc whereas mine builds opencv4.pc. And I even checked the doumentation for OpenCV 4.2.0. Even this one quotes "Installed as `opencv4`, usage: `pkg-config --cflags --libs opencv4`". [OpenCV-4.2.0_Linux_Installation](https://docs.opencv.org/4.2.0/d7/d9f/tutorial_linux_install.html)

Maybe you also have a version of `opencv` which you might have installed through `apt-get`. Please do check this.

**Comment by leezu** [comment]
Thanks @shawnbrar for the elaboration. The issue will be fixed by https://github.com/apache/incubator-mxnet/pull/17404/ shortly.

**Comment by shawnbrar** [comment]
You're welcome. I've been dying to try this library in R since mid 2019. But wasn't able to build it properly earlier.

**Comment by leezu** [comment]
@shawnbrar I fixed some issues with the R build recently, so at least the build should work well now. Please report any further issues you fine here on github

**Comment by shawnbrar** [comment]
> @shawnbrar I fixed some issues with the R build recently, so at least the build should work well now. Please report any further issues you fine here on github

@leezu, were you able to find out whether the build on your Ubuntu was using OpenCV 4 or OpenCV 3?

**Comment by leezu** [comment]
It was with OpenCV 3. The fix in #17404 will apply to Ubuntu 20.04 and current Debian Testing, as well as when manually compiling OpenCV 4 from source and installing it correctly.

**Comment by shawnbrar** [comment]
@leezu , Bro, I reinstalled ubuntu again on my laptop. I built OpenBLAS, MKL-DNN, the I built R and installed RStudio. Then, I built mxnet and then its R-package. The error about `No package 'opencv' found` still persists, even when I built it using the changes that you've made. The whole error output is below.
_________________________________________________________________________
`$ make -f R-package/Makefile rpkg
mkdir -p R-package/inst/libs
cp src/io/image_recordio.h R-package/src
if [ -d "lib" ]; then \
	cp -rf lib/libmxnet.so R-package/inst/libs; \
	if [ -e "lib/libtvm_runtime.so" ]; then \
		cp -rf lib/libtvm_runtime.so R-package/inst/libs; \
	fi; \
else \
	cp -rf build/libmxnet.so R-package/inst/libs; \
	if [ -e "build/libtvm_runtime.so" ]; then \
		cp -rf build/libtvm_runtime.so R-package/inst/libs; \
	fi; \
fi
mkdir -p R-package/inst/include
cp -rl include/* R-package/inst/include
Rscript -e "if(!require(devtools)){install.packages('devtools', repo = 'https://cloud.r-project.org/')}"
Loading required package: devtools
Loading required package: usethis
Rscript -e "if(!require(roxygen2)||packageVersion('roxygen2') < '6.1.1'){install.packages('roxygen2', repo = 'https://cloud.r-project.org/')}"
Loading required package: roxygen2
Rscript -e "library(devtools); library(methods); options(repos=c(CRAN='https://cloud.r-project.org/')); install_deps(pkg='R-package', dependencies = TRUE)"
Loading required package: usethis
jsonlite (1.6 -> 1.6.1) [CRAN]
mime     (0.8 -> 0.9  ) [CRAN]
Installing 2 packages: jsonlite, mime
Installing packages into ‘/home/shawn/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/jsonlite_1.6.1.tar.gz'
Content type 'application/x-gzip' length 1057910 bytes (1.0 MB)
==================================================
downloaded 1.0 MB

trying URL 'https://cloud.r-project.org/src/contrib/mime_0.9.tar.gz'
Content type 'application/x-gzip' length 12843 bytes (12 KB)
==================================================
downloaded 12 KB

* installing *source* package ‘jsonlite’ ...
** package ‘jsonlite’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
make[1]: Entering directory '/tmp/RtmpckmmqM/R.INSTALL87267a48938/jsonlite/src'
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api   -fvisibility=hidden  -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-t3diwe/r-base-3.6.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c base64.c -o base64.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api   -fvisibility=hidden  -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-t3diwe/r-base-3.6.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c collapse_array.c -o collapse_array.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api   -fvisibility=hidden  -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-t3diwe/r-base-3.6.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c collapse_object.c -o collapse_object.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api   -fvisibility=hidden  -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-t3diwe/r-base-3.6.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c collapse_pretty.c -o collapse_pretty.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api   -fvisibility=hidden  -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-t3diwe/r-base-3.6.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c escape_chars.c -o escape_chars.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api   -fvisibility=hidden  -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-t3diwe/r-base-3.6.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c integer64_to_na.c -o integer64_to_na.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api   -fvisibility=hidden  -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-t3diwe/r-base-3.6.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c is_datelist.c -o is_datelist.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api   -fvisibility=hidden  -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-t3diwe/r-base-3.6.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c is_recordlist.c -o is_recordlist.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api   -fvisibility=hidden  -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-t3diwe/r-base-3.6.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c is_scalarlist.c -o is_scalarlist.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api   -fvisibility=hidden  -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-t3diwe/r-base-3.6.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c modp_numtoa.c -o modp_numtoa.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api   -fvisibility=hidden  -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-t3diwe/r-base-3.6.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c null_to_na.c -o null_to_na.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api   -fvisibility=hidden  -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-t3diwe/r-base-3.6.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c num_to_char.c -o num_to_char.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api   -fvisibility=hidden  -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-t3diwe/r-base-3.6.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c parse.c -o parse.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api   -fvisibility=hidden  -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-t3diwe/r-base-3.6.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c prettify.c -o prettify.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api   -fvisibility=hidden  -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-t3diwe/r-base-3.6.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c push_parser.c -o push_parser.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api   -fvisibility=hidden  -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-t3diwe/r-base-3.6.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c r-base64.c -o r-base64.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api   -fvisibility=hidden  -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-t3diwe/r-base-3.6.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c register.c -o register.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api   -fvisibility=hidden  -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-t3diwe/r-base-3.6.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c row_collapse.c -o row_collapse.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api   -fvisibility=hidden  -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-t3diwe/r-base-3.6.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c transpose_list.c -o transpose_list.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api   -fvisibility=hidden  -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-t3diwe/r-base-3.6.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c validate.c -o validate.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api   -fvisibility=hidden  -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-t3diwe/r-base-3.6.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c yajl/yajl.c -o yajl/yajl.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api   -fvisibility=hidden  -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-t3diwe/r-base-3.6.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c yajl/yajl_alloc.c -o yajl/yajl_alloc.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api   -fvisibility=hidden  -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-t3diwe/r-base-3.6.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c yajl/yajl_buf.c -o yajl/yajl_buf.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api   -fvisibility=hidden  -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-t3diwe/r-base-3.6.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c yajl/yajl_encode.c -o yajl/yajl_encode.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api   -fvisibility=hidden  -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-t3diwe/r-base-3.6.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c yajl/yajl_gen.c -o yajl/yajl_gen.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api   -fvisibility=hidden  -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-t3diwe/r-base-3.6.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c yajl/yajl_lex.c -o yajl/yajl_lex.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api   -fvisibility=hidden  -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-t3diwe/r-base-3.6.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c yajl/yajl_parser.c -o yajl/yajl_parser.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -Iyajl/api   -fvisibility=hidden  -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-t3diwe/r-base-3.6.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c yajl/yajl_tree.c -o yajl/yajl_tree.o
ar rcs yajl/libstatyajl.a yajl/yajl.o yajl/yajl_alloc.o yajl/yajl_buf.o yajl/yajl_encode.o yajl/yajl_gen.o yajl/yajl_lex.o yajl/yajl_parser.o yajl/yajl_tree.o
gcc -std=gnu99 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o jsonlite.so base64.o collapse_array.o collapse_object.o collapse_pretty.o escape_chars.o integer64_to_na.o is_datelist.o is_recordlist.o is_scalarlist.o modp_numtoa.o null_to_na.o num_to_char.o parse.o prettify.o push_parser.o r-base64.o register.o row_collapse.o transpose_list.o validate.o -Lyajl -lstatyajl -L/usr/lib/R/lib -lR
make[1]: Leaving directory '/tmp/RtmpckmmqM/R.INSTALL87267a48938/jsonlite/src'
installing to /home/shawn/R/x86_64-pc-linux-gnu-library/3.6/00LOCK-jsonlite/00new/jsonlite/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (jsonlite)
* installing *source* package ‘mime’ ...
** package ‘mime’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
make[1]: Entering directory '/tmp/Rtmpx6mi0N/R.INSTALL908492fe057/mime/src'
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-t3diwe/r-base-3.6.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c init.c -o init.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-t3diwe/r-base-3.6.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c rawmatch.c -o rawmatch.o
gcc -std=gnu99 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o mime.so init.o rawmatch.o -L/usr/lib/R/lib -lR
make[1]: Leaving directory '/tmp/Rtmpx6mi0N/R.INSTALL908492fe057/mime/src'
installing to /home/shawn/R/x86_64-pc-linux-gnu-library/3.6/00LOCK-mime/00new/mime/libs
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (mime)

The downloaded source packages are in
	‘/tmp/RtmpUGsQck/downloaded_packages’
cp R-package/dummy.NAMESPACE R-package/NAMESPACE  # NAMESPACE will be replaced by devtools::document later
echo "import(Rcpp)" >> R-package/NAMESPACE
R CMD INSTALL R-package
* installing to library ‘/home/shawn/R/x86_64-pc-linux-gnu-library/3.6’
* installing *source* package ‘mxnet’ ...
** using staged installation
** libs
make[1]: Entering directory '/home/shawn/Documents/Libs/mxnet/R-package/src'
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -I../inst/include `(pkg-config --cflags opencv || pkg-config --cflags opencv4)` `Rscript -e 'Rcpp:::CxxFlags()'` -I"/home/shawn/R/x86_64-pc-linux-gnu-library/3.6/Rcpp/include"   -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-t3diwe/r-base-3.6.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c executor.cc -o executor.o
Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found
In file included from executor.cc:28:0:
././symbol.h: In destructor ‘mxnet::R::Symbol::~Symbol()’:
./base.h:102:45: warning: throw will always call terminate() [-Wterminate]
       throw Rcpp::exception(MXGetLastError());                     \
                                             ^
././symbol.h:138:5: note: in expansion of macro ‘MX_CALL’
     MX_CALL(MXSymbolFree(handle_));
     ^
./base.h:102:45: note: in C++11 destructors default to noexcept
       throw Rcpp::exception(MXGetLastError());                     \
                                             ^
././symbol.h:138:5: note: in expansion of macro ‘MX_CALL’
     MX_CALL(MXSymbolFree(handle_));
     ^
./executor.h: In destructor ‘mxnet::R::Executor::~Executor()’:
./base.h:102:45: warning: throw will always call terminate() [-Wterminate]
       throw Rcpp::exception(MXGetLastError());                     \
                                             ^
./executor.h:158:7: note: in expansion of macro ‘MX_CALL’
       MX_CALL(MXExecutorFree(handle_));
       ^
./base.h:102:45: note: in C++11 destructors default to noexcept
       throw Rcpp::exception(MXGetLastError());                     \
                                             ^
./executor.h:158:7: note: in expansion of macro ‘MX_CALL’
       MX_CALL(MXExecutorFree(handle_));
       ^
./ndarray.h: In destructor ‘mxnet::R::NDBlob::~NDBlob()’:
./base.h:102:45: warning: throw will always call terminate() [-Wterminate]
       throw Rcpp::exception(MXGetLastError());                     \
                                             ^
./ndarray.h:54:7: note: in expansion of macro ‘MX_CALL’
       MX_CALL(MXNDArrayFree(handle));
       ^
./base.h:102:45: note: in C++11 destructors default to noexcept
       throw Rcpp::exception(MXGetLastError());                     \
                                             ^
./ndarray.h:54:7: note: in expansion of macro ‘MX_CALL’
       MX_CALL(MXNDArrayFree(handle));
       ^
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -I../inst/include `(pkg-config --cflags opencv || pkg-config --cflags opencv4)` `Rscript -e 'Rcpp:::CxxFlags()'` -I"/home/shawn/R/x86_64-pc-linux-gnu-library/3.6/Rcpp/include"   -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-t3diwe/r-base-3.6.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c export.cc -o export.o
Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -I../inst/include `(pkg-config --cflags opencv || pkg-config --cflags opencv4)` `Rscript -e 'Rcpp:::CxxFlags()'` -I"/home/shawn/R/x86_64-pc-linux-gnu-library/3.6/Rcpp/include"   -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-t3diwe/r-base-3.6.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c im2rec.cc -o im2rec.o
Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -I../inst/include `(pkg-config --cflags opencv || pkg-config --cflags opencv4)` `Rscript -e 'Rcpp:::CxxFlags()'` -I"/home/shawn/R/x86_64-pc-linux-gnu-library/3.6/Rcpp/include"   -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-t3diwe/r-base-3.6.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c io.cc -o io.o
Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found
In file included from io.cc:27:0:
././ndarray.h: In destructor ‘mxnet::R::NDBlob::~NDBlob()’:
./base.h:102:45: warning: throw will always call terminate() [-Wterminate]
       throw Rcpp::exception(MXGetLastError());                     \
                                             ^
././ndarray.h:54:7: note: in expansion of macro ‘MX_CALL’
       MX_CALL(MXNDArrayFree(handle));
       ^
./base.h:102:45: note: in C++11 destructors default to noexcept
       throw Rcpp::exception(MXGetLastError());                     \
                                             ^
././ndarray.h:54:7: note: in expansion of macro ‘MX_CALL’
       MX_CALL(MXNDArrayFree(handle));
       ^
./io.h: In destructor ‘virtual mxnet::R::MXDataIter::~MXDataIter()’:
./base.h:102:45: warning: throw will always call terminate() [-Wterminate]
       throw Rcpp::exception(MXGetLastError());                     \
                                             ^
./io.h:84:5: note: in expansion of macro ‘MX_CALL’
     MX_CALL(MXDataIterFree(handle_));
     ^
./base.h:102:45: note: in C++11 destructors default to noexcept
       throw Rcpp::exception(MXGetLastError());                     \
                                             ^
./io.h:84:5: note: in expansion of macro ‘MX_CALL’
     MX_CALL(MXDataIterFree(handle_));
     ^
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -I../inst/include `(pkg-config --cflags opencv || pkg-config --cflags opencv4)` `Rscript -e 'Rcpp:::CxxFlags()'` -I"/home/shawn/R/x86_64-pc-linux-gnu-library/3.6/Rcpp/include"   -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-t3diwe/r-base-3.6.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c kvstore.cc -o kvstore.o
Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found
In file included from kvstore.cc:28:0:
./kvstore.h: In destructor ‘mxnet::R::KVStore::~KVStore()’:
./base.h:102:45: warning: throw will always call terminate() [-Wterminate]
       throw Rcpp::exception(MXGetLastError());                     \
                                             ^
./kvstore.h:92:5: note: in expansion of macro ‘MX_CALL’
     MX_CALL(MXKVStoreFree(handle_));
     ^
./base.h:102:45: note: in C++11 destructors default to noexcept
       throw Rcpp::exception(MXGetLastError());                     \
                                             ^
./kvstore.h:92:5: note: in expansion of macro ‘MX_CALL’
     MX_CALL(MXKVStoreFree(handle_));
     ^
./ndarray.h: In destructor ‘mxnet::R::NDBlob::~NDBlob()’:
./base.h:102:45: warning: throw will always call terminate() [-Wterminate]
       throw Rcpp::exception(MXGetLastError());                     \
                                             ^
./ndarray.h:54:7: note: in expansion of macro ‘MX_CALL’
       MX_CALL(MXNDArrayFree(handle));
       ^
./base.h:102:45: note: in C++11 destructors default to noexcept
       throw Rcpp::exception(MXGetLastError());                     \
                                             ^
./ndarray.h:54:7: note: in expansion of macro ‘MX_CALL’
       MX_CALL(MXNDArrayFree(handle));
       ^
^C/usr/lib/R/etc/Makeconf:175: recipe for target 'kvstore.o' failed
make[1]: *** [kvstore.o] Interrupt
ERROR: compilation failed for package ‘mxnet’
* removing ‘/home/shawn/R/x86_64-pc-linux-gnu-library/3.6/mxnet’
R-package/Makefile:5: recipe for target 'rpkg' failed
make: *** [rpkg] Interrupt`
_________________________________________________________________________

Please check this. I, once more, had to rename my `opencv4.pc` to `opencv.pc`.
(Sorry for the bad formatting)

**Comment by leezu** [comment]
Probably your PKG_CONFIG_PATH is wrong.

**Comment by shawnbrar** [comment]
I am using the latest master version. And if my PKG_CONFIG_PATH is wrong, then changing opencv4.pc to opencv.pc shouldn't work.

**Comment by leezu** [comment]
Try editing https://github.com/apache/incubator-mxnet/pull/17404/files instead of renaming opencv4.pc to opencv.pc. Any improvements to that PR are welcome.
