### ISSUE TITLE
Test break for some ops if bound max error instead of mean error.

### ISSUE THREAD

**Issue by piiswrong** [apache/incubator-mxnet#3997]
Some of the tests in test operators will break when you change mx.test_utils.reldiff to this
```
def reldiff(a, b):
    """Calculate the relative difference between two input arrays

    Calculated by :math:`\\frac{|a-b|_1}{|a|_1 + |b|_1}`

    Parameters
    ----------
    a : np.ndarray
    b : np.ndarray
    """
    diff = np.abs(a - b)
    norm = np.maximum(np.abs(a), np.abs(b)) + 1e-7
    ret = np.max(diff / norm)
    return ret
```

The difference is we were limiting average error instead of max error. However I think limiting max error is the right approach since averaging can hide error if it only occur in a small number of locations (say boundaries).

Here is the list of OP that need to be fixed:
ROIPooling @precedenceguo 
instance_normalization @sbodenstein 
l2_normalization @winstywang @zhreshold 
```
jxie@jxie-gpu:/scratch/mxnet$ nosetests tests/python/unittest/test_operator.py
..........................[18:37:13] src/operator/./reshape-inl.h:311: Using target_shape will be deprecated.
..............E.EE...
======================================================================
ERROR: test_operator.test_roipooling
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jxie/anaconda2/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/scratch/mxnet/tests/python/unittest/test_operator.py", line 1513, in test_roipooling
    check_numeric_gradient(test, [x1, x2], numeric_eps=1e-3, check_eps=1e-2)
  File "/scratch/mxnet/python/mxnet/test_utils.py", line 391, in check_numeric_gradient
    raise Exception(msg)
Exception: 
Items are not equal:
In symbol "roipooling0", ctx=cpu(0), numeric check failed for "data", grad_req= "write". Rel Err=0.080857, Expected <=0.010000
 NUMERICAL: array([[[[ 0.        ,  0.        ,  0.        , ...,  0.        ,
           0.        ,  0.        ],
         [ 0.        ,  0.99182129,  0.74768066, ...,  0.79345703,...
 BACKWARD: array([[[[ 0.        ,  0.        ,  0.        , ...,  0.        ,
           0.        ,  0.        ],
         [ 0.        ,  0.98034358,  0.73739147, ...,  0.79384667,...

======================================================================
ERROR: test_operator.test_instance_normalization
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jxie/anaconda2/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/scratch/mxnet/tests/python/unittest/test_operator.py", line 1584, in test_instance_normalization
    check_instance_norm_with_shape((2,4,5,6), default_context())
  File "/scratch/mxnet/tests/python/unittest/test_operator.py", line 1580, in check_instance_norm_with_shape
    check_numeric_gradient(Y, {'X':x.asnumpy(), 'G':gamma.asnumpy(), 'B':beta.asnumpy()}, numeric_eps=1e-2, check_eps=0.16)
  File "/scratch/mxnet/python/mxnet/test_utils.py", line 391, in check_numeric_gradient
    raise Exception(msg)
Exception: 
Items are not equal:
In symbol "instancenorm0", ctx=cpu(0), numeric check failed for "X", grad_req= "write". Rel Err=0.999591, Expected <=0.160000
 NUMERICAL: array([[[[-0.00801086, -0.05378723,  0.02403259,  0.06256104,  0.11444092,
          -0.09994507],
         [-0.04386902, -0.06942749, -0.01373291,  0.03128052,  0.01487732,...
 BACKWARD: array([[[[-0.00833133, -0.05397411,  0.02389139,  0.0623968 ,  0.11421351,
          -0.0999947 ],
         [-0.0441424 , -0.06971355, -0.01379509,  0.0310756 ,  0.01470332,...

======================================================================
ERROR: test_operator.test_l2_normalization
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jxie/anaconda2/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/scratch/mxnet/tests/python/unittest/test_operator.py", line 1627, in test_l2_normalization
    check_l2_normalization((nbatch, nchannel, height, width), mode)
  File "/scratch/mxnet/tests/python/unittest/test_operator.py", line 1617, in check_l2_normalization
    check_numeric_gradient(out, [in_data], numeric_eps=1e-3, check_eps=0.1)
  File "/scratch/mxnet/python/mxnet/test_utils.py", line 391, in check_numeric_gradient
    raise Exception(msg)
Exception: 
Items are not equal:
In symbol "l2normalization2", ctx=cpu(0), numeric check failed for "data", grad_req= "write". Rel Err=0.942003, Expected <=0.100000
 NUMERICAL: array([[[[ 0.80013275,  1.99604034,  0.0667572 , ...,  0.52928925,
           0.39577484,  0.41103363],
         [ 0.12493134,  0.37193298,  0.1707077 , ...,  0.0629425 ,...
 BACKWARD: array([[[[ 0.80023903,  1.99528956,  0.06625256, ...,  0.52785367,
           0.39663202,  0.41160059],
         [ 0.12542851,  0.37282375,  0.17115563, ...,  0.06351195,...

----------------------------------------------------------------------
Ran 47 tests in 6.841s

FAILED (errors=3)
```

**Comment by zhreshold** [comment]
Will look into these. Are these three Ops the the entire list that will be affected by the change? 
Symptoms are quite similar and Ops are all normalization related.

**Comment by piiswrong** [comment]
There are some others but they can be fixed by change tol from 0.01 to 0.02 or 0.05. These cannot be fixed no matter what

**Comment by zhreshold** [comment]
I found the NUMERICAL gradient is really not stable. I've printed out some results in l2_normalization.
```
numeric_eps=1e-2
 NUMERICAL: array([[[ 0.81679821,  0.45166016,  1.20382309,  0.52347183],
        [ 0.6206274 ,  0.42130947,  1.79920197, -0.12338161],
        [ 0.01583099,  1.38514042, -0.04489422,  0.85744858]]], dtype=float32)
 BACKWARD: array([[[ 0.8199982 ,  0.45682225,  1.22095621,  0.53185207],
        [ 0.62182719,  0.42369154,  1.80545735, -0.12479854],
        [ 0.01606028,  1.37370849, -0.04382877,  0.86594933]]], dtype=float32)

numeric_eps=1e-3

NUMERICAL: array([[[ 0.81968307,  0.45633316,  1.21927261,  0.53119659],
        [ 0.62179565,  0.42366982,  1.80482864, -0.1244545 ],
        [ 0.01621246,  1.37519836, -0.04386902,  0.86545944]]], dtype=float32)
 BACKWARD: array([[[ 0.8199982 ,  0.45682225,  1.22095621,  0.53185207],
        [ 0.62182719,  0.42369154,  1.80545735, -0.12479854],
        [ 0.01606028,  1.37370849, -0.04382877,  0.86594933]]], dtype=float32)


numeric_eps=1e-4

 NUMERICAL: array([[[ 0.82015991,  0.45776367,  1.22070312,  0.53405762],
        [ 0.62227249,  0.42676926,  1.80721283, -0.12397766],
        [ 0.0166893 ,  1.3756752 , -0.04291534,  0.86784363]]], dtype=float32)
 BACKWARD: array([[[ 0.8199982 ,  0.45682225,  1.22095621,  0.53185207],
        [ 0.62182719,  0.42369154,  1.80545735, -0.12479854],
        [ 0.01606028,  1.37370849, -0.04382877,  0.86594933]]], dtype=float32)

numeric_eps=1e-5

 NUMERICAL: array([[[ 0.83446503,  0.47683716,  1.21593475,  0.54836273],
        [ 0.64373016,  0.4529953 ,  1.8119812 , -0.11920929],
        [ 0.04768372,  1.38282776, -0.02384186,  0.88214874]]], dtype=float32)
 BACKWARD: array([[[ 0.8199982 ,  0.45682225,  1.22095621,  0.53185207],
        [ 0.62182719,  0.42369154,  1.80545735, -0.12479854],
        [ 0.01606028,  1.37370849, -0.04382877,  0.86594933]]], dtype=float32)

numeric_eps=1e-6

 NUMERICAL: array([[[ 0.95367432,  0.47683716,  1.1920929 ,  0.71525574],
        [ 0.71525574,  0.47683716,  1.90734863,  0.        ],
        [ 0.23841858,  1.43051147,  0.        ,  0.95367432]]], dtype=float32)
 BACKWARD: array([[[ 0.8199982 ,  0.45682225,  1.22095621,  0.53185207],
        [ 0.62182719,  0.42369154,  1.80545735, -0.12479854],
        [ 0.01606028,  1.37370849, -0.04382877,  0.86594933]]], dtype=float32)
```
By comparing NUMERICAL gradients using different numeric_eps, I somehow suspect there's something wrong with the check_numeric_gradient function. But I need to confirm that. Will update later.

**Comment by zhreshold** [comment]
Okay, the original numeric_gradient uses (f(x + h) - f(x)) / h instead of the centered difference method (f(x + h) - f(x -h)) / 2h, #3693, which resulted in very imprecise estimated gradients.  
PR #3824 fixed this. However, ROIPooling still breaks(due to other reason I guess)
@piiswrong

**Comment by piiswrong** [comment]
https://github.com/dmlc/mxnet/pull/3824/files This Pr also use central diff but wasn't merged due to test fail.
Are you interested in taking over? If ROI is the only thing that's failing and you can't fix it, we can disable it first and wait for @precedenceguo to take a look

**Comment by precedenceguo** [comment]
I attempted to find out the gradient check problem of ROIPooling but failed to tell why. So should it be moved to separate folders like the ssd example?

**Comment by sxjscience** [comment]
@piiswrong @precedenceguo The error in https://github.com/dmlc/mxnet/pull/3824 could be fixed. I need some time to finish other works before digging into this...

**Comment by zhreshold** [comment]
The reason why ROIPooling breaks is quite simple. Gradient check should not be performed on rois.

https://github.com/dmlc/mxnet/pull/3824/files#diff-cb652780258e73a9cd08568f38929aa2L1473
```
check_numeric_gradient(test, [x1, x2], grad_nodes={'data':'write', 'rois':'null'}, numeric_eps=1e-3, check_eps=1e-2)
check_numeric_gradient(sym=test, location=[x1, x2],
                           grad_nodes={'data':'add', 'rois':'null'},
                           numeric_eps=1e-3, check_eps=1e-2)
```
Tested OK, not necessarily to change x2
@piiswrong @precedenceguo @sxjscience 
Do you still want me to take the PR over? It just need a minor fix.

**Comment by piiswrong** [comment]
the original guy wasn't responding. You are welcome to do it. Are you sure
roi shouldnt be grad tested? I thought we have end to end training now?

**Comment by zhreshold** [comment]
No gradient is generated for rois, the loss for rpn is from different path.

**Comment by sxjscience** [comment]
@zhreshold Thanks! This should solve the problem.

**Comment by piiswrong** [comment]
Looks like that PR was reactivated. Could you take a look? https://github.com/dmlc/mxnet/pull/3824
@precedenceguo Could you confirm this? Does RPN use grad for rois? I vaguely remembered it does differentiation wrt bilinear sampling

**Comment by sxjscience** [comment]
The implemented ROI Pooling uses the max operator and will pass back zero-gradient. Should be OK.

**Comment by zhreshold** [comment]
My bad, merging #3824 reverted the reldiff() function. The original problem is still UNSOLVED.  The PR itself should be good.

**Comment by precedenceguo** [comment]
Yes, the end-to-end is approximate. rois will pass zero-gradient.
