### ISSUE TITLE
accuracy of cpp example is a constant value when training, no matter how many epochs trained!

### ISSUE THREAD

**Issue by goodtogood** [apache/incubator-mxnet#7725]
cpp example : lenet_with_mxdataiter(gpu and cpu)  mlp_cpu mlp_gpu

I've tested examples on three PCs (win8.1 64bit && win2012 64bit && centos7 64bit ) , 
roughly it's same, just mlp_gpu works correctly.

## Environment info  Operating System && Compiler

win8.1 64bit && win2012 64bit  ===>  vs2017 cmake
centos7 64bit                              ===>  gcc

Package used:                                          cpp

MXNet version:      installed from source

MXNet commit hash (`git rev-parse HEAD`): 

SHA-1: 6d7157768e216bcb4b505f98555fc72286d160fb

## Error Message:
accuracy is a constant value , no matter how many epochs trained
please refer to attached images.

## Minimum reproducible example
no modification just run after compiled

## Steps to reproduce
no modification just run after compilederror.

## What have you tried to solve it?
run example on other PCs

![lenet_with_mxdataiter_on_centos7](https://user-images.githubusercontent.com/10088733/30034131-f017192e-91d1-11e7-8dc0-58f93c8744ab.png)

![lenet_with_mxdataiter_on_win81](https://user-images.githubusercontent.com/10088733/30034235-a23e39de-91d2-11e7-8929-a251ae5fec35.png)

![lenet_with_mxdataiter_on_win2012](https://user-images.githubusercontent.com/10088733/30034239-a6359e42-91d2-11e7-9b00-56e7bd99d6f1.png)

![mlp_cpu_on_centos7](https://user-images.githubusercontent.com/10088733/30034143-ff7f1240-91d1-11e7-8f2e-5520292da983.png)

![mlp_cpu_on_win81](https://user-images.githubusercontent.com/10088733/30034241-acdaf080-91d2-11e7-94fb-b48db31592f4.png)

![mlp_cpu_on_win2012](https://user-images.githubusercontent.com/10088733/30034154-067f6ad6-91d2-11e7-81d2-e696ba1153e8.png)

**Comment by goodtogood** [comment]
@piiswrong @mli

**Comment by goodtogood** [comment]
nobody cares about cpp ?

**Comment by eric-haibin-lin** [comment]
ping @lx75249

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by chsin** [comment]
@goodtogood if you pull master and rebuild, do you have the same issue? Apparently, the fix was merged: https://github.com/apache/incubator-mxnet/pull/8551. I'm curious bc I've just built master, but have the same problem with lenet.cpp

**Comment by lebeg** [comment]
Can this issue be resolved?

**Comment by marcoabreu** [comment]
Hello @chsin, please check if your issue has been resolved with #8551.

**Comment by sandeep-krishnamurthy** [comment]
Resolving in favor of #8551 . Please reopen if issue still persists.
