### ISSUE TITLE
CI fails to create Nvidia driver from time to time

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#9440]
I see this error message multiple times on CI and it seems to be related to CI instead of MXNet source code. I wonder if anyone is working on fixing this? @marcoabreu @KellenSunderland @pedro 

```
docker: Error response from daemon: create nvidia_driver_384.111: VolumeDriver.Create: internal error, check logs for details.

See 'docker run --help'.

```
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/master/169/pipeline

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/master/170/pipeline

**Comment by marcoabreu** [comment]
This was related to the Spectre security update, released as a security critical patch and thus automatically applied to all our slaves. This was related to https://lists.apache.org/thread.html/142e5602d26bdb27801c31319187a5a44261065a26730dde1c963b0e@%3Cdev.mxnet.apache.org%3E. The problem has been fixed now. Feel free to log into the CI and retrigger the build yourself.

**Comment by zheng-da** [comment]
@marcoabreu It seems to me that building a new docker still fails. It still fails with the same error.

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-9423/12/pipeline/59

**Comment by marcoabreu** [comment]
Thank you, I have noted it down.
